// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MsgLiteExt.proto

package MsgLiteExt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgLiteInner struct {
	ProtoType            *uint32  `protobuf:"varint,1,req,name=protoType" json:"protoType,omitempty"`
	ProtoData            []byte   `protobuf:"bytes,2,opt,name=protoData" json:"protoData,omitempty"`
	ProtoClientNo        *uint32  `protobuf:"varint,3,opt,name=protoClientNo" json:"protoClientNo,omitempty"`
	ProtoBackExp         *string  `protobuf:"bytes,4,opt,name=protoBackExp" json:"protoBackExp,omitempty"`
	ProtoSource          *string  `protobuf:"bytes,5,opt,name=protoSource" json:"protoSource,omitempty"`
	ProtoErrorCode       *uint32  `protobuf:"varint,6,opt,name=protoErrorCode" json:"protoErrorCode,omitempty"`
	ProtoEncrypt         *uint32  `protobuf:"varint,7,opt,name=protoEncrypt" json:"protoEncrypt,omitempty"`
	ProtoToken           *string  `protobuf:"bytes,8,opt,name=protoToken" json:"protoToken,omitempty"`
	ProtoRouter          *string  `protobuf:"bytes,9,opt,name=protoRouter" json:"protoRouter,omitempty"`
	ProtoDestId          *string  `protobuf:"bytes,10,opt,name=protoDestId" json:"protoDestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLiteInner) Reset()         { *m = MsgLiteInner{} }
func (m *MsgLiteInner) String() string { return proto.CompactTextString(m) }
func (*MsgLiteInner) ProtoMessage()    {}
func (*MsgLiteInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_465c98963c69c1e5, []int{0}
}

func (m *MsgLiteInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiteInner.Unmarshal(m, b)
}
func (m *MsgLiteInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiteInner.Marshal(b, m, deterministic)
}
func (m *MsgLiteInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiteInner.Merge(m, src)
}
func (m *MsgLiteInner) XXX_Size() int {
	return xxx_messageInfo_MsgLiteInner.Size(m)
}
func (m *MsgLiteInner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiteInner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiteInner proto.InternalMessageInfo

func (m *MsgLiteInner) GetProtoType() uint32 {
	if m != nil && m.ProtoType != nil {
		return *m.ProtoType
	}
	return 0
}

func (m *MsgLiteInner) GetProtoData() []byte {
	if m != nil {
		return m.ProtoData
	}
	return nil
}

func (m *MsgLiteInner) GetProtoClientNo() uint32 {
	if m != nil && m.ProtoClientNo != nil {
		return *m.ProtoClientNo
	}
	return 0
}

func (m *MsgLiteInner) GetProtoBackExp() string {
	if m != nil && m.ProtoBackExp != nil {
		return *m.ProtoBackExp
	}
	return ""
}

func (m *MsgLiteInner) GetProtoSource() string {
	if m != nil && m.ProtoSource != nil {
		return *m.ProtoSource
	}
	return ""
}

func (m *MsgLiteInner) GetProtoErrorCode() uint32 {
	if m != nil && m.ProtoErrorCode != nil {
		return *m.ProtoErrorCode
	}
	return 0
}

func (m *MsgLiteInner) GetProtoEncrypt() uint32 {
	if m != nil && m.ProtoEncrypt != nil {
		return *m.ProtoEncrypt
	}
	return 0
}

func (m *MsgLiteInner) GetProtoToken() string {
	if m != nil && m.ProtoToken != nil {
		return *m.ProtoToken
	}
	return ""
}

func (m *MsgLiteInner) GetProtoRouter() string {
	if m != nil && m.ProtoRouter != nil {
		return *m.ProtoRouter
	}
	return ""
}

func (m *MsgLiteInner) GetProtoDestId() string {
	if m != nil && m.ProtoDestId != nil {
		return *m.ProtoDestId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgLiteInner)(nil), "MsgLiteInner")
}

func init() { proto.RegisterFile("MsgLiteExt.proto", fileDescriptor_465c98963c69c1e5) }

var fileDescriptor_465c98963c69c1e5 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd0, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x07, 0x70, 0x92, 0x7e, 0x9f, 0x35, 0x63, 0x22, 0xb2, 0xa7, 0x41, 0x44, 0x96, 0x22, 0x9a,
	0x53, 0x0f, 0x82, 0x0f, 0x60, 0xdb, 0x50, 0x0b, 0xea, 0x61, 0xeb, 0x0b, 0x84, 0x74, 0xd0, 0x50,
	0xd9, 0x0d, 0xdb, 0x89, 0xb4, 0x2f, 0xec, 0x73, 0x08, 0x13, 0x49, 0x37, 0x1e, 0xff, 0xbf, 0xf9,
	0xc3, 0xcc, 0x2e, 0x5c, 0xbc, 0xec, 0xde, 0x9f, 0x6b, 0xa6, 0x62, 0xcf, 0xd3, 0xc6, 0x3b, 0x76,
	0x93, 0xef, 0x18, 0xd2, 0x5f, 0x5c, 0x59, 0x4b, 0x5e, 0x5d, 0x41, 0x22, 0x93, 0xb7, 0x43, 0x43,
	0x18, 0xe9, 0x38, 0xcf, 0xcc, 0x11, 0xfa, 0xe9, 0xa2, 0xe4, 0x12, 0x63, 0x1d, 0xe5, 0xa9, 0x39,
	0x82, 0xba, 0x81, 0x4c, 0xc2, 0xfc, 0xb3, 0x26, 0xcb, 0xaf, 0x0e, 0x47, 0x3a, 0xca, 0x33, 0x33,
	0x44, 0x35, 0x81, 0x54, 0x60, 0x56, 0x56, 0xdb, 0x62, 0xdf, 0xe0, 0x3f, 0x1d, 0xe5, 0x89, 0x19,
	0x98, 0xd2, 0x70, 0x26, 0x79, 0xed, 0x5a, 0x5f, 0x11, 0xfe, 0x97, 0x4a, 0x48, 0xea, 0x16, 0xce,
	0x25, 0x16, 0xde, 0x3b, 0x3f, 0x77, 0x1b, 0xc2, 0x13, 0x59, 0xf6, 0x47, 0xfb, 0x6d, 0x85, 0xad,
	0xfc, 0xa1, 0x61, 0x1c, 0x4b, 0x6b, 0x60, 0xea, 0x1a, 0xa0, 0x7b, 0xa2, 0xdb, 0x92, 0xc5, 0x53,
	0x59, 0x16, 0x48, 0x7f, 0x8d, 0x71, 0x2d, 0x93, 0xc7, 0x24, 0xb8, 0xa6, 0xa3, 0xbe, 0xb1, 0xa0,
	0x1d, 0xaf, 0x36, 0x08, 0x41, 0xa3, 0xa3, 0xfb, 0x07, 0x80, 0x25, 0xf1, 0x9a, 0xfc, 0x57, 0x5d,
	0x91, 0xba, 0x83, 0xf1, 0x92, 0xf8, 0xb1, 0xe5, 0x0f, 0x95, 0x4d, 0xc3, 0xff, 0xbf, 0x1c, 0xc6,
	0x59, 0xfc, 0x34, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x91, 0x6c, 0xca, 0xb6, 0x01, 0x00,
	0x00,
}
