// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SendMsgBlackWordResp.proto

package SendMsgBlackWordResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMsgBlackWordResp struct {
	ExtOpts              *string  `protobuf:"bytes,1,opt,name=extOpts" json:"extOpts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgBlackWordResp) Reset()         { *m = SendMsgBlackWordResp{} }
func (m *SendMsgBlackWordResp) String() string { return proto.CompactTextString(m) }
func (*SendMsgBlackWordResp) ProtoMessage()    {}
func (*SendMsgBlackWordResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef24eff9cf6c564c, []int{0}
}

func (m *SendMsgBlackWordResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgBlackWordResp.Unmarshal(m, b)
}
func (m *SendMsgBlackWordResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgBlackWordResp.Marshal(b, m, deterministic)
}
func (m *SendMsgBlackWordResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgBlackWordResp.Merge(m, src)
}
func (m *SendMsgBlackWordResp) XXX_Size() int {
	return xxx_messageInfo_SendMsgBlackWordResp.Size(m)
}
func (m *SendMsgBlackWordResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgBlackWordResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgBlackWordResp proto.InternalMessageInfo

func (m *SendMsgBlackWordResp) GetExtOpts() string {
	if m != nil && m.ExtOpts != nil {
		return *m.ExtOpts
	}
	return ""
}

func init() {
	proto.RegisterType((*SendMsgBlackWordResp)(nil), "SendMsgBlackWordResp")
}

func init() { proto.RegisterFile("SendMsgBlackWordResp.proto", fileDescriptor_ef24eff9cf6c564c) }

var fileDescriptor_ef24eff9cf6c564c = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x0a, 0x4e, 0xcd, 0x4b,
	0xf1, 0x2d, 0x4e, 0x77, 0xca, 0x49, 0x4c, 0xce, 0x0e, 0xcf, 0x2f, 0x4a, 0x09, 0x4a, 0x2d, 0x2e,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe0, 0x12, 0xc1, 0x26, 0x2b, 0x24, 0xc1, 0xc5,
	0x9e, 0x5a, 0x51, 0xe2, 0x5f, 0x50, 0x52, 0x2c, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3,
	0x3a, 0xa9, 0x71, 0x29, 0x25, 0xe7, 0xe7, 0xea, 0x55, 0x96, 0xe6, 0x95, 0xe4, 0xe7, 0xa5, 0x57,
	0x94, 0xe6, 0xe9, 0xe5, 0xe4, 0xa7, 0x67, 0x26, 0xeb, 0x25, 0xe7, 0x17, 0xa5, 0x42, 0x0c, 0x4d,
	0x2a, 0x4d, 0xf3, 0x60, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x89, 0xb7, 0x2c, 0x9e, 0x76, 0x00,
	0x00, 0x00,
}
