// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SendMsg.proto

package SendMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMsgInner struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msgType" json:"msgType,omitempty"`
	MsgId                *string  `protobuf:"bytes,2,opt,name=msgId" json:"msgId,omitempty"`
	MsgContent           []byte   `protobuf:"bytes,3,opt,name=msgContent" json:"msgContent,omitempty"`
	MsgSender            *string  `protobuf:"bytes,4,opt,name=msgSender" json:"msgSender,omitempty"`
	MsgReceiver          *string  `protobuf:"bytes,5,opt,name=msgReceiver" json:"msgReceiver,omitempty"`
	MsgDomain            *string  `protobuf:"bytes,6,opt,name=msgDomain" json:"msgDomain,omitempty"`
	MsgFileName          *string  `protobuf:"bytes,7,opt,name=msgFileName" json:"msgFileName,omitempty"`
	MsgCompressLen       *uint32  `protobuf:"varint,8,opt,name=msgCompressLen" json:"msgCompressLen,omitempty"`
	MsgData              []byte   `protobuf:"bytes,9,opt,name=msgData" json:"msgData,omitempty"`
	Anonymity            *uint32  `protobuf:"varint,10,opt,name=anonymity" json:"anonymity,omitempty"`
	ExtOpts              *string  `protobuf:"bytes,11,opt,name=extOpts" json:"extOpts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgInner) Reset()         { *m = SendMsgInner{} }
func (m *SendMsgInner) String() string { return proto.CompactTextString(m) }
func (*SendMsgInner) ProtoMessage()    {}
func (*SendMsgInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63b23d8dc237af1, []int{0}
}

func (m *SendMsgInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgInner.Unmarshal(m, b)
}
func (m *SendMsgInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgInner.Marshal(b, m, deterministic)
}
func (m *SendMsgInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgInner.Merge(m, src)
}
func (m *SendMsgInner) XXX_Size() int {
	return xxx_messageInfo_SendMsgInner.Size(m)
}
func (m *SendMsgInner) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgInner.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgInner proto.InternalMessageInfo

func (m *SendMsgInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *SendMsgInner) GetMsgId() string {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return ""
}

func (m *SendMsgInner) GetMsgContent() []byte {
	if m != nil {
		return m.MsgContent
	}
	return nil
}

func (m *SendMsgInner) GetMsgSender() string {
	if m != nil && m.MsgSender != nil {
		return *m.MsgSender
	}
	return ""
}

func (m *SendMsgInner) GetMsgReceiver() string {
	if m != nil && m.MsgReceiver != nil {
		return *m.MsgReceiver
	}
	return ""
}

func (m *SendMsgInner) GetMsgDomain() string {
	if m != nil && m.MsgDomain != nil {
		return *m.MsgDomain
	}
	return ""
}

func (m *SendMsgInner) GetMsgFileName() string {
	if m != nil && m.MsgFileName != nil {
		return *m.MsgFileName
	}
	return ""
}

func (m *SendMsgInner) GetMsgCompressLen() uint32 {
	if m != nil && m.MsgCompressLen != nil {
		return *m.MsgCompressLen
	}
	return 0
}

func (m *SendMsgInner) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *SendMsgInner) GetAnonymity() uint32 {
	if m != nil && m.Anonymity != nil {
		return *m.Anonymity
	}
	return 0
}

func (m *SendMsgInner) GetExtOpts() string {
	if m != nil && m.ExtOpts != nil {
		return *m.ExtOpts
	}
	return ""
}

func init() {
	proto.RegisterType((*SendMsgInner)(nil), "SendMsgInner")
}

func init() { proto.RegisterFile("SendMsg.proto", fileDescriptor_f63b23d8dc237af1) }

var fileDescriptor_f63b23d8dc237af1 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x6a, 0xad, 0x99, 0xb6, 0x1e, 0x16, 0x0f, 0x73, 0x10, 0x09, 0x1e, 0x24, 0x27,
	0x1f, 0x42, 0x8b, 0x58, 0xf0, 0x0f, 0x44, 0x5f, 0x60, 0xb1, 0xc3, 0x12, 0x70, 0x66, 0xc3, 0xce,
	0x22, 0xe6, 0x4d, 0x7d, 0x1c, 0xc9, 0x36, 0x69, 0x43, 0x8f, 0xdf, 0x6f, 0xf8, 0x31, 0xdf, 0x07,
	0xeb, 0x0f, 0x92, 0xdd, 0xab, 0xba, 0xfb, 0x36, 0xf8, 0xe8, 0x6f, 0xff, 0x72, 0x58, 0x0d, 0x64,
	0x2b, 0x42, 0xc1, 0x20, 0x2c, 0x58, 0xdd, 0x67, 0xd7, 0x12, 0x66, 0x65, 0x56, 0xad, 0xeb, 0x31,
	0x9a, 0x2b, 0x98, 0xb3, 0xba, 0xed, 0x0e, 0xf3, 0x32, 0xab, 0x8a, 0x7a, 0x1f, 0xcc, 0x0d, 0x00,
	0xab, 0x7b, 0xf4, 0x12, 0x49, 0x22, 0xce, 0xca, 0xac, 0x5a, 0xd5, 0x13, 0x62, 0xae, 0xa1, 0x60,
	0x75, 0xfd, 0x0b, 0x0a, 0x78, 0x96, 0xcc, 0x23, 0x30, 0x25, 0x2c, 0x59, 0x5d, 0x4d, 0x5f, 0xd4,
	0xfc, 0x50, 0xc0, 0x79, 0xba, 0x4f, 0xd1, 0xe0, 0x6f, 0x3c, 0xdb, 0x46, 0xf0, 0xfc, 0xe0, 0xef,
	0xc1, 0xe0, 0x3f, 0x35, 0xdf, 0xf4, 0x66, 0x99, 0x70, 0x71, 0xf0, 0x47, 0x64, 0xee, 0xe0, 0x32,
	0xb5, 0xe1, 0x36, 0x90, 0xea, 0x0b, 0x09, 0x5e, 0xa4, 0x59, 0x27, 0x74, 0xd8, 0xbd, 0xb1, 0xd1,
	0x62, 0x91, 0x46, 0x8c, 0xb1, 0x6f, 0x60, 0xc5, 0x4b, 0xc7, 0x4d, 0xec, 0x10, 0x92, 0x7c, 0x04,
	0xbd, 0x47, 0xbf, 0xf1, 0xbd, 0x8d, 0x8a, 0xcb, 0xf4, 0x7d, 0x8c, 0x0f, 0xf9, 0xf3, 0xec, 0x3f,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x2b, 0x63, 0x79, 0x6e, 0x01, 0x00, 0x00,
}
