// Code generated by protoc-gen-go. DO NOT EDIT.
// source: NoticeMsg.proto

package NoticeMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NoticeMsgInner struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msgType" json:"msgType,omitempty"`
	MsgId                *string  `protobuf:"bytes,2,opt,name=msgId" json:"msgId,omitempty"`
	PushType             *uint32  `protobuf:"varint,3,opt,name=pushType" json:"pushType,omitempty"`
	MsgContent           []byte   `protobuf:"bytes,4,opt,name=msgContent" json:"msgContent,omitempty"`
	MsgSender            *string  `protobuf:"bytes,5,opt,name=msgSender" json:"msgSender,omitempty"`
	MsgDomain            *string  `protobuf:"bytes,6,opt,name=msgDomain" json:"msgDomain,omitempty"`
	MsgFileName          *string  `protobuf:"bytes,7,opt,name=msgFileName" json:"msgFileName,omitempty"`
	DateCreated          *string  `protobuf:"bytes,8,opt,name=dateCreated" json:"dateCreated,omitempty"`
	FileUrl              *string  `protobuf:"bytes,9,opt,name=fileUrl" json:"fileUrl,omitempty"`
	MsgCompressLen       *uint32  `protobuf:"varint,10,opt,name=msgCompressLen" json:"msgCompressLen,omitempty"`
	MsgLength            *uint32  `protobuf:"varint,11,opt,name=msgLength" json:"msgLength,omitempty"`
	MsgFileSize          *uint32  `protobuf:"varint,12,opt,name=msgFileSize" json:"msgFileSize,omitempty"`
	SenderNickName       *string  `protobuf:"bytes,13,opt,name=senderNickName" json:"senderNickName,omitempty"`
	MsgData              *string  `protobuf:"bytes,14,opt,name=msgData" json:"msgData,omitempty"`
	RealReceivers        []string `protobuf:"bytes,15,rep,name=realReceivers" json:"realReceivers,omitempty"`
	GroupId              *string  `protobuf:"bytes,16,opt,name=groupId" json:"groupId,omitempty"`
	MsgLocalName         *string  `protobuf:"bytes,17,opt,name=msgLocalName" json:"msgLocalName,omitempty"`
	ExtOpts              *string  `protobuf:"bytes,18,opt,name=extOpts" json:"extOpts,omitempty"`
	Path                 *string  `protobuf:"bytes,19,opt,name=path" json:"path,omitempty"`
	ExtBusines           *uint32  `protobuf:"varint,20,opt,name=extBusines" json:"extBusines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeMsgInner) Reset()         { *m = NoticeMsgInner{} }
func (m *NoticeMsgInner) String() string { return proto.CompactTextString(m) }
func (*NoticeMsgInner) ProtoMessage()    {}
func (*NoticeMsgInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_e39bce20cd9951e0, []int{0}
}

func (m *NoticeMsgInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeMsgInner.Unmarshal(m, b)
}
func (m *NoticeMsgInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeMsgInner.Marshal(b, m, deterministic)
}
func (m *NoticeMsgInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeMsgInner.Merge(m, src)
}
func (m *NoticeMsgInner) XXX_Size() int {
	return xxx_messageInfo_NoticeMsgInner.Size(m)
}
func (m *NoticeMsgInner) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeMsgInner.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeMsgInner proto.InternalMessageInfo

func (m *NoticeMsgInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *NoticeMsgInner) GetMsgId() string {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return ""
}

func (m *NoticeMsgInner) GetPushType() uint32 {
	if m != nil && m.PushType != nil {
		return *m.PushType
	}
	return 0
}

func (m *NoticeMsgInner) GetMsgContent() []byte {
	if m != nil {
		return m.MsgContent
	}
	return nil
}

func (m *NoticeMsgInner) GetMsgSender() string {
	if m != nil && m.MsgSender != nil {
		return *m.MsgSender
	}
	return ""
}

func (m *NoticeMsgInner) GetMsgDomain() string {
	if m != nil && m.MsgDomain != nil {
		return *m.MsgDomain
	}
	return ""
}

func (m *NoticeMsgInner) GetMsgFileName() string {
	if m != nil && m.MsgFileName != nil {
		return *m.MsgFileName
	}
	return ""
}

func (m *NoticeMsgInner) GetDateCreated() string {
	if m != nil && m.DateCreated != nil {
		return *m.DateCreated
	}
	return ""
}

func (m *NoticeMsgInner) GetFileUrl() string {
	if m != nil && m.FileUrl != nil {
		return *m.FileUrl
	}
	return ""
}

func (m *NoticeMsgInner) GetMsgCompressLen() uint32 {
	if m != nil && m.MsgCompressLen != nil {
		return *m.MsgCompressLen
	}
	return 0
}

func (m *NoticeMsgInner) GetMsgLength() uint32 {
	if m != nil && m.MsgLength != nil {
		return *m.MsgLength
	}
	return 0
}

func (m *NoticeMsgInner) GetMsgFileSize() uint32 {
	if m != nil && m.MsgFileSize != nil {
		return *m.MsgFileSize
	}
	return 0
}

func (m *NoticeMsgInner) GetSenderNickName() string {
	if m != nil && m.SenderNickName != nil {
		return *m.SenderNickName
	}
	return ""
}

func (m *NoticeMsgInner) GetMsgData() string {
	if m != nil && m.MsgData != nil {
		return *m.MsgData
	}
	return ""
}

func (m *NoticeMsgInner) GetRealReceivers() []string {
	if m != nil {
		return m.RealReceivers
	}
	return nil
}

func (m *NoticeMsgInner) GetGroupId() string {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return ""
}

func (m *NoticeMsgInner) GetMsgLocalName() string {
	if m != nil && m.MsgLocalName != nil {
		return *m.MsgLocalName
	}
	return ""
}

func (m *NoticeMsgInner) GetExtOpts() string {
	if m != nil && m.ExtOpts != nil {
		return *m.ExtOpts
	}
	return ""
}

func (m *NoticeMsgInner) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *NoticeMsgInner) GetExtBusines() uint32 {
	if m != nil && m.ExtBusines != nil {
		return *m.ExtBusines
	}
	return 0
}

func init() {
	proto.RegisterType((*NoticeMsgInner)(nil), "NoticeMsgInner")
}

func init() { proto.RegisterFile("NoticeMsg.proto", fileDescriptor_e39bce20cd9951e0) }

var fileDescriptor_e39bce20cd9951e0 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xdd, 0x8e, 0xda, 0x30,
	0x14, 0x84, 0x15, 0x7e, 0x0a, 0x31, 0x7f, 0xad, 0xcb, 0xc5, 0x51, 0x55, 0x55, 0x11, 0xaa, 0xaa,
	0x5c, 0xf5, 0x21, 0x00, 0x55, 0x45, 0xa2, 0x54, 0x0a, 0xbb, 0x0f, 0x60, 0x25, 0x67, 0x8d, 0xb5,
	0xb1, 0x13, 0xd9, 0x66, 0xc5, 0xee, 0x63, 0xef, 0x13, 0xac, 0x72, 0x12, 0x20, 0x70, 0x97, 0xf9,
	0xc6, 0x13, 0xcf, 0xc8, 0x6c, 0xb6, 0x2b, 0xbc, 0x4a, 0xf1, 0x9f, 0x93, 0xbf, 0x4b, 0x5b, 0xf8,
	0x62, 0xf1, 0xde, 0x63, 0xd3, 0x0b, 0xdb, 0x18, 0x83, 0x96, 0x03, 0x1b, 0x68, 0x27, 0x1f, 0x5e,
	0x4b, 0x84, 0x20, 0x0a, 0xe2, 0x49, 0x72, 0x96, 0x7c, 0xce, 0xfa, 0xda, 0xc9, 0x4d, 0x06, 0x9d,
	0x28, 0x88, 0xc3, 0xa4, 0x16, 0xfc, 0x1b, 0x1b, 0x96, 0x47, 0x77, 0xa0, 0x40, 0x97, 0x02, 0x17,
	0xcd, 0x7f, 0x30, 0xa6, 0x9d, 0x5c, 0x15, 0xc6, 0xa3, 0xf1, 0xd0, 0x8b, 0x82, 0x78, 0x9c, 0xb4,
	0x08, 0xff, 0xce, 0x42, 0xed, 0xe4, 0x1e, 0x4d, 0x86, 0x16, 0xfa, 0xf4, 0xd7, 0x2b, 0x68, 0xdc,
	0x75, 0xa1, 0x85, 0x32, 0xf0, 0xe9, 0xe2, 0xd6, 0x80, 0x47, 0x6c, 0xa4, 0x9d, 0xfc, 0xa3, 0x72,
	0xdc, 0x09, 0x8d, 0x30, 0x20, 0xbf, 0x8d, 0xaa, 0x13, 0x99, 0xf0, 0xb8, 0xb2, 0x28, 0x3c, 0x66,
	0x30, 0xac, 0x4f, 0xb4, 0x50, 0xb5, 0xf5, 0x49, 0xe5, 0xf8, 0x68, 0x73, 0x08, 0xc9, 0x3d, 0x4b,
	0xfe, 0x8b, 0x4d, 0xa9, 0xa7, 0x2e, 0x2d, 0x3a, 0xb7, 0x45, 0x03, 0x8c, 0xb6, 0xdd, 0xd1, 0xa6,
	0xe3, 0x16, 0x8d, 0xf4, 0x07, 0x18, 0xd1, 0x91, 0x2b, 0x68, 0x75, 0xdc, 0xab, 0x37, 0x84, 0x31,
	0xf9, 0x6d, 0x54, 0xdd, 0xe3, 0x68, 0xed, 0x4e, 0xa5, 0xcf, 0x34, 0x64, 0x42, 0x45, 0xee, 0x68,
	0xf3, 0x2a, 0x6b, 0xe1, 0x05, 0x4c, 0xeb, 0xa6, 0x8d, 0xe4, 0x3f, 0xd9, 0xc4, 0xa2, 0xc8, 0x13,
	0x4c, 0x51, 0xbd, 0xa0, 0x75, 0x30, 0x8b, 0xba, 0x71, 0x98, 0xdc, 0xc2, 0x2a, 0x2f, 0x6d, 0x71,
	0x2c, 0x37, 0x19, 0x7c, 0xae, 0xf3, 0x8d, 0xe4, 0x0b, 0x36, 0xae, 0x0a, 0x17, 0xa9, 0xc8, 0xe9,
	0xfe, 0x2f, 0x64, 0xdf, 0xb0, 0x2a, 0x8d, 0x27, 0xff, 0xbf, 0xf4, 0x0e, 0x78, 0x9d, 0x6e, 0x24,
	0xe7, 0xac, 0x57, 0x0a, 0x7f, 0x80, 0xaf, 0x84, 0xe9, 0xbb, 0x7a, 0x75, 0x3c, 0xf9, 0xe5, 0xd1,
	0x29, 0x83, 0x0e, 0xe6, 0x34, 0xba, 0x45, 0x96, 0x9d, 0xbf, 0xdd, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x74, 0xfb, 0x7e, 0x20, 0x8a, 0x02, 0x00, 0x00,
}
