// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PushGroupMsg.proto

package PushGroupMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushGroupMsgInner struct {
	Version              *uint64  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	MsgType              *uint32  `protobuf:"varint,2,opt,name=msgType" json:"msgType,omitempty"`
	MsgId                *string  `protobuf:"bytes,3,opt,name=msgId" json:"msgId,omitempty"`
	MsgContent           []byte   `protobuf:"bytes,4,opt,name=msgContent" json:"msgContent,omitempty"`
	MsgSender            *string  `protobuf:"bytes,5,opt,name=msgSender" json:"msgSender,omitempty"`
	MsgReceiver          *string  `protobuf:"bytes,6,opt,name=msgReceiver" json:"msgReceiver,omitempty"`
	MsgDomain            *string  `protobuf:"bytes,7,opt,name=msgDomain" json:"msgDomain,omitempty"`
	MsgFileName          *string  `protobuf:"bytes,8,opt,name=msgFileName" json:"msgFileName,omitempty"`
	MsgFileUrl           *string  `protobuf:"bytes,9,opt,name=msgFileUrl" json:"msgFileUrl,omitempty"`
	MsgDateCreated       *string  `protobuf:"bytes,10,opt,name=msgDateCreated" json:"msgDateCreated,omitempty"`
	MsgCompressLen       *uint32  `protobuf:"varint,11,opt,name=msgCompressLen" json:"msgCompressLen,omitempty"`
	MsgData              []byte   `protobuf:"bytes,12,opt,name=msgData" json:"msgData,omitempty"`
	SenderNickName       *string  `protobuf:"bytes,13,opt,name=senderNickName" json:"senderNickName,omitempty"`
	MsgFileSize          *string  `protobuf:"bytes,14,opt,name=msgFileSize" json:"msgFileSize,omitempty"`
	ExtOpts              *string  `protobuf:"bytes,15,opt,name=extOpts" json:"extOpts,omitempty"`
	GroupId              *uint64  `protobuf:"varint,16,opt,name=groupId" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushGroupMsgInner) Reset()         { *m = PushGroupMsgInner{} }
func (m *PushGroupMsgInner) String() string { return proto.CompactTextString(m) }
func (*PushGroupMsgInner) ProtoMessage()    {}
func (*PushGroupMsgInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_981bd3d20b2aed4d, []int{0}
}

func (m *PushGroupMsgInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushGroupMsgInner.Unmarshal(m, b)
}
func (m *PushGroupMsgInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushGroupMsgInner.Marshal(b, m, deterministic)
}
func (m *PushGroupMsgInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushGroupMsgInner.Merge(m, src)
}
func (m *PushGroupMsgInner) XXX_Size() int {
	return xxx_messageInfo_PushGroupMsgInner.Size(m)
}
func (m *PushGroupMsgInner) XXX_DiscardUnknown() {
	xxx_messageInfo_PushGroupMsgInner.DiscardUnknown(m)
}

var xxx_messageInfo_PushGroupMsgInner proto.InternalMessageInfo

func (m *PushGroupMsgInner) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *PushGroupMsgInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *PushGroupMsgInner) GetMsgId() string {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgContent() []byte {
	if m != nil {
		return m.MsgContent
	}
	return nil
}

func (m *PushGroupMsgInner) GetMsgSender() string {
	if m != nil && m.MsgSender != nil {
		return *m.MsgSender
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgReceiver() string {
	if m != nil && m.MsgReceiver != nil {
		return *m.MsgReceiver
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgDomain() string {
	if m != nil && m.MsgDomain != nil {
		return *m.MsgDomain
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgFileName() string {
	if m != nil && m.MsgFileName != nil {
		return *m.MsgFileName
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgFileUrl() string {
	if m != nil && m.MsgFileUrl != nil {
		return *m.MsgFileUrl
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgDateCreated() string {
	if m != nil && m.MsgDateCreated != nil {
		return *m.MsgDateCreated
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgCompressLen() uint32 {
	if m != nil && m.MsgCompressLen != nil {
		return *m.MsgCompressLen
	}
	return 0
}

func (m *PushGroupMsgInner) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *PushGroupMsgInner) GetSenderNickName() string {
	if m != nil && m.SenderNickName != nil {
		return *m.SenderNickName
	}
	return ""
}

func (m *PushGroupMsgInner) GetMsgFileSize() string {
	if m != nil && m.MsgFileSize != nil {
		return *m.MsgFileSize
	}
	return ""
}

func (m *PushGroupMsgInner) GetExtOpts() string {
	if m != nil && m.ExtOpts != nil {
		return *m.ExtOpts
	}
	return ""
}

func (m *PushGroupMsgInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*PushGroupMsgInner)(nil), "PushGroupMsgInner")
}

func init() { proto.RegisterFile("PushGroupMsg.proto", fileDescriptor_981bd3d20b2aed4d) }

var fileDescriptor_981bd3d20b2aed4d = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcb, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0x5e, 0xfe, 0xfe, 0x75, 0x2f, 0x80, 0xc5, 0x62, 0x16, 0x08, 0x45, 0x2c, 0x50,
	0x56, 0x3c, 0x04, 0xad, 0x80, 0x4a, 0x50, 0x50, 0x0a, 0x0f, 0x10, 0x35, 0x23, 0x63, 0x51, 0xdb,
	0x91, 0xc7, 0xad, 0x80, 0x3d, 0xef, 0x8d, 0xec, 0x38, 0x25, 0xed, 0xf2, 0x7c, 0x67, 0x8e, 0x3d,
	0x17, 0xc6, 0x5f, 0xb6, 0xf4, 0x7e, 0x6f, 0xcd, 0xb6, 0x7a, 0x22, 0x71, 0x53, 0x59, 0xe3, 0xcc,
	0xd5, 0x4f, 0x8f, 0x9d, 0xb5, 0xf1, 0x42, 0x6b, 0xb4, 0x1c, 0xd8, 0x60, 0x87, 0x96, 0xa4, 0xd1,
	0x90, 0xa4, 0x49, 0xd6, 0xcb, 0x1b, 0xe9, 0x1d, 0x45, 0xe2, 0xf5, 0xab, 0x42, 0xe8, 0xa4, 0x49,
	0x36, 0xc9, 0x1b, 0xc9, 0xcf, 0x59, 0x5f, 0x91, 0x58, 0x94, 0xd0, 0x4d, 0x93, 0x6c, 0x98, 0xd7,
	0x82, 0x5f, 0x32, 0xa6, 0x48, 0xcc, 0x8c, 0x76, 0xa8, 0x1d, 0xf4, 0xd2, 0x24, 0x1b, 0xe7, 0x2d,
	0xc2, 0x2f, 0xd8, 0x50, 0x91, 0x58, 0xa1, 0x2e, 0xd1, 0x42, 0x3f, 0x24, 0xff, 0x00, 0x4f, 0xd9,
	0x48, 0x91, 0xc8, 0x71, 0x8d, 0x72, 0x87, 0x16, 0xfe, 0x05, 0xbf, 0x8d, 0x62, 0x7e, 0x6e, 0x54,
	0x21, 0x35, 0x0c, 0xf6, 0xf9, 0x1a, 0xc4, 0xfc, 0x9d, 0xdc, 0xe0, 0xb2, 0x50, 0x08, 0xff, 0xf7,
	0xf9, 0x06, 0xc5, 0xfe, 0xbc, 0x7c, 0xb3, 0x1b, 0x18, 0x86, 0x82, 0x16, 0xe1, 0xd7, 0x6c, 0xea,
	0x9f, 0x2b, 0x1c, 0xce, 0x2c, 0x16, 0x0e, 0x4b, 0x60, 0xa1, 0xe6, 0x88, 0xc6, 0xba, 0x99, 0x51,
	0x95, 0x45, 0xa2, 0x47, 0xd4, 0x30, 0x0a, 0xeb, 0x39, 0xa2, 0x71, 0x7f, 0xf3, 0xc2, 0x15, 0x30,
	0x0e, 0xcb, 0x68, 0xa4, 0x7f, 0x81, 0xc2, 0xd4, 0x4b, 0xb9, 0xfe, 0x08, 0xed, 0x4e, 0xea, 0x9f,
	0x0e, 0x69, 0x6b, 0xa6, 0x95, 0xfc, 0x46, 0x98, 0x1e, 0xcc, 0xe4, 0x91, 0xff, 0x03, 0x3f, 0xdd,
	0x73, 0xe5, 0x08, 0x4e, 0x82, 0xdb, 0x48, 0xef, 0x08, 0x7f, 0xe8, 0x45, 0x09, 0xa7, 0xf5, 0x5d,
	0xa3, 0xbc, 0xed, 0x3c, 0x74, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x5c, 0x46, 0xd7, 0x20,
	0x02, 0x00, 0x00,
}
