// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MsgData.proto

package comm

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgDataInner struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msgType" json:"msgType,omitempty"`
	MsgData              []byte   `protobuf:"bytes,2,opt,name=msgData" json:"msgData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgDataInner) Reset()         { *m = MsgDataInner{} }
func (m *MsgDataInner) String() string { return proto.CompactTextString(m) }
func (*MsgDataInner) ProtoMessage()    {}
func (*MsgDataInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_890dd7da69d4615a, []int{0}
}

func (m *MsgDataInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgDataInner.Unmarshal(m, b)
}
func (m *MsgDataInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgDataInner.Marshal(b, m, deterministic)
}
func (m *MsgDataInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDataInner.Merge(m, src)
}
func (m *MsgDataInner) XXX_Size() int {
	return xxx_messageInfo_MsgDataInner.Size(m)
}
func (m *MsgDataInner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDataInner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDataInner proto.InternalMessageInfo

func (m *MsgDataInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *MsgDataInner) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgDataInner)(nil), "MsgDataInner")
}

func init() { proto.RegisterFile("MsgData.proto", fileDescriptor_890dd7da69d4615a) }

var fileDescriptor_890dd7da69d4615a = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x2d, 0x4e, 0x77,
	0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe2, 0xe2, 0x81, 0x0a, 0x78,
	0xe6, 0xe5, 0xa5, 0x16, 0x09, 0x49, 0x70, 0xb1, 0xe7, 0x16, 0xa7, 0x87, 0x54, 0x16, 0xa4, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0xc1, 0xb8, 0x50, 0x19, 0x90, 0x4a, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0x9e, 0x20, 0x18, 0xd7, 0x89, 0xc9, 0x83, 0x19, 0x10, 0x00, 0x00, 0xff, 0xff, 0x81, 0x5e,
	0xa5, 0x7f, 0x57, 0x00, 0x00, 0x00,
}
