// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MsgLite.proto

package comm

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgLiteInner struct {
	ProtoType            *uint32  `protobuf:"varint,1,req,name=protoType" json:"protoType,omitempty"`
	ProtoData            []byte   `protobuf:"bytes,2,opt,name=protoData" json:"protoData,omitempty"`
	ProtoClientNo        *uint32  `protobuf:"varint,3,opt,name=protoClientNo" json:"protoClientNo,omitempty"`
	ProtoBackExp         *string  `protobuf:"bytes,4,opt,name=protoBackExp" json:"protoBackExp,omitempty"`
	ProtoSource          *string  `protobuf:"bytes,5,opt,name=protoSource" json:"protoSource,omitempty"`
	ProtoErrorCode       *uint32  `protobuf:"varint,6,opt,name=protoErrorCode" json:"protoErrorCode,omitempty"`
	ProtoEncrypt         *uint32  `protobuf:"varint,7,opt,name=protoEncrypt" json:"protoEncrypt,omitempty"`
	ProtoToken           *string  `protobuf:"bytes,8,opt,name=protoToken" json:"protoToken,omitempty"`
	ProtoRouter          *string  `protobuf:"bytes,9,opt,name=protoRouter" json:"protoRouter,omitempty"`
	ProtoDestId          *string  `protobuf:"bytes,10,opt,name=protoDestId" json:"protoDestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgLiteInner) Reset()         { *m = MsgLiteInner{} }
func (m *MsgLiteInner) String() string { return proto.CompactTextString(m) }
func (*MsgLiteInner) ProtoMessage()    {}
func (*MsgLiteInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0b7be2c1366d5d2, []int{0}
}

func (m *MsgLiteInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiteInner.Unmarshal(m, b)
}
func (m *MsgLiteInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiteInner.Marshal(b, m, deterministic)
}
func (m *MsgLiteInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiteInner.Merge(m, src)
}
func (m *MsgLiteInner) XXX_Size() int {
	return xxx_messageInfo_MsgLiteInner.Size(m)
}
func (m *MsgLiteInner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiteInner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiteInner proto.InternalMessageInfo

func (m *MsgLiteInner) GetProtoType() uint32 {
	if m != nil && m.ProtoType != nil {
		return *m.ProtoType
	}
	return 0
}

func (m *MsgLiteInner) GetProtoData() []byte {
	if m != nil {
		return m.ProtoData
	}
	return nil
}

func (m *MsgLiteInner) GetProtoClientNo() uint32 {
	if m != nil && m.ProtoClientNo != nil {
		return *m.ProtoClientNo
	}
	return 0
}

func (m *MsgLiteInner) GetProtoBackExp() string {
	if m != nil && m.ProtoBackExp != nil {
		return *m.ProtoBackExp
	}
	return ""
}

func (m *MsgLiteInner) GetProtoSource() string {
	if m != nil && m.ProtoSource != nil {
		return *m.ProtoSource
	}
	return ""
}

func (m *MsgLiteInner) GetProtoErrorCode() uint32 {
	if m != nil && m.ProtoErrorCode != nil {
		return *m.ProtoErrorCode
	}
	return 0
}

func (m *MsgLiteInner) GetProtoEncrypt() uint32 {
	if m != nil && m.ProtoEncrypt != nil {
		return *m.ProtoEncrypt
	}
	return 0
}

func (m *MsgLiteInner) GetProtoToken() string {
	if m != nil && m.ProtoToken != nil {
		return *m.ProtoToken
	}
	return ""
}

func (m *MsgLiteInner) GetProtoRouter() string {
	if m != nil && m.ProtoRouter != nil {
		return *m.ProtoRouter
	}
	return ""
}

func (m *MsgLiteInner) GetProtoDestId() string {
	if m != nil && m.ProtoDestId != nil {
		return *m.ProtoDestId
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgLiteInner)(nil), "MsgLiteInner")
}

func init() { proto.RegisterFile("MsgLite.proto", fileDescriptor_d0b7be2c1366d5d2) }

var fileDescriptor_d0b7be2c1366d5d2 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x06, 0x70, 0x92, 0xfa, 0x2f, 0x63, 0xe2, 0x61, 0x4f, 0x73, 0x10, 0x59, 0x8a, 0x48, 0x4e,
	0x3e, 0x44, 0xdb, 0x80, 0x05, 0xf5, 0xb0, 0xfa, 0x02, 0x21, 0x1d, 0xa4, 0x54, 0x76, 0x96, 0xe9,
	0x16, 0xec, 0x0b, 0xfb, 0x1c, 0xc2, 0x44, 0xb6, 0x9b, 0x1e, 0xbf, 0xdf, 0x7e, 0xf0, 0xcd, 0x42,
	0xf3, 0xb6, 0xff, 0x7a, 0xdd, 0x46, 0x7a, 0x0e, 0xc2, 0x91, 0xe7, 0xbf, 0x25, 0xd4, 0xff, 0xb2,
	0xf6, 0x9e, 0xc4, 0xdc, 0x43, 0xa5, 0x2f, 0x9f, 0xc7, 0x40, 0x58, 0xd8, 0xb2, 0x6d, 0xdc, 0x09,
	0xd2, 0xeb, 0xaa, 0x8f, 0x3d, 0x96, 0xb6, 0x68, 0x6b, 0x77, 0x02, 0xf3, 0x08, 0x8d, 0x86, 0xe5,
	0xf7, 0x96, 0x7c, 0x7c, 0x67, 0x9c, 0xd9, 0xa2, 0x6d, 0xdc, 0x14, 0xcd, 0x1c, 0x6a, 0x85, 0x45,
	0x3f, 0xec, 0xba, 0x9f, 0x80, 0x17, 0xb6, 0x68, 0x2b, 0x37, 0x31, 0x63, 0xe1, 0x56, 0xf3, 0x07,
	0x1f, 0x64, 0x20, 0xbc, 0xd4, 0x4a, 0x4e, 0xe6, 0x09, 0xee, 0x34, 0x76, 0x22, 0x2c, 0x4b, 0xde,
	0x10, 0x5e, 0xe9, 0xd8, 0x99, 0xa6, 0xb5, 0xce, 0x0f, 0x72, 0x0c, 0x11, 0xaf, 0xb5, 0x35, 0x31,
	0xf3, 0x00, 0x30, 0x7e, 0x91, 0x77, 0xe4, 0xf1, 0x46, 0xc7, 0x32, 0x49, 0xd7, 0x38, 0x3e, 0x44,
	0x12, 0xac, 0xb2, 0x6b, 0x46, 0x4a, 0x8d, 0x15, 0xed, 0xe3, 0x7a, 0x83, 0x90, 0x35, 0x46, 0x5a,
	0x94, 0x2f, 0xb3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x52, 0x6b, 0xb0, 0xaa, 0x7c, 0x01, 0x00,
	0x00,
}
