// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Logout.proto

package auth

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogoutInner struct {
	DeviceNo             *string  `protobuf:"bytes,1,opt,name=deviceNo" json:"deviceNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutInner) Reset()         { *m = LogoutInner{} }
func (m *LogoutInner) String() string { return proto.CompactTextString(m) }
func (*LogoutInner) ProtoMessage()    {}
func (*LogoutInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_40eb2b0add235440, []int{0}
}

func (m *LogoutInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutInner.Unmarshal(m, b)
}
func (m *LogoutInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutInner.Marshal(b, m, deterministic)
}
func (m *LogoutInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutInner.Merge(m, src)
}
func (m *LogoutInner) XXX_Size() int {
	return xxx_messageInfo_LogoutInner.Size(m)
}
func (m *LogoutInner) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutInner.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutInner proto.InternalMessageInfo

func (m *LogoutInner) GetDeviceNo() string {
	if m != nil && m.DeviceNo != nil {
		return *m.DeviceNo
	}
	return ""
}

func init() {
	proto.RegisterType((*LogoutInner)(nil), "LogoutInner")
}

func init() { proto.RegisterFile("Logout.proto", fileDescriptor_40eb2b0add235440) }

var fileDescriptor_40eb2b0add235440 = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf1, 0xc9, 0x4f, 0xcf,
	0x2f, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe4, 0xe2, 0x86, 0xf0, 0x3d, 0xf3,
	0xf2, 0x52, 0x8b, 0x84, 0xa4, 0xb8, 0x38, 0x52, 0x52, 0xcb, 0x32, 0x93, 0x53, 0xfd, 0xf2, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x27, 0x26, 0x0f, 0x66, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xe9, 0x7a, 0x64, 0x69, 0x3d, 0x00, 0x00, 0x00,
}
