// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UserAuth.proto

package auth

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserAuthInner struct {
	AuthType             *uint32  `protobuf:"varint,1,opt,name=authType,def=1" json:"authType,omitempty"`
	AppId                *string  `protobuf:"bytes,2,opt,name=appId" json:"appId,omitempty"`
	UserName             *string  `protobuf:"bytes,3,opt,name=userName" json:"userName,omitempty"`
	Timestamp            *string  `protobuf:"bytes,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Device               *uint32  `protobuf:"varint,5,opt,name=device" json:"device,omitempty"`
	Sig                  *string  `protobuf:"bytes,6,opt,name=sig" json:"sig,omitempty"`
	SdkVersion           *string  `protobuf:"bytes,7,opt,name=sdkVersion" json:"sdkVersion,omitempty"`
	Imei                 *string  `protobuf:"bytes,8,opt,name=imei" json:"imei,omitempty"`
	Mode                 *uint32  `protobuf:"varint,9,opt,name=mode" json:"mode,omitempty"`
	Network              *uint32  `protobuf:"varint,10,opt,name=network" json:"network,omitempty"`
	Pwd                  *string  `protobuf:"bytes,11,opt,name=pwd" json:"pwd,omitempty"`
	Bundleid             *string  `protobuf:"bytes,12,opt,name=bundleid" json:"bundleid,omitempty"`
	SubDevice            *string  `protobuf:"bytes,13,opt,name=subDevice" json:"subDevice,omitempty"`
	Language             *string  `protobuf:"bytes,14,opt,name=language" json:"language,omitempty"`
	UserId               *uint64  `protobuf:"varint,15,opt,name=userId" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthInner) Reset()         { *m = UserAuthInner{} }
func (m *UserAuthInner) String() string { return proto.CompactTextString(m) }
func (*UserAuthInner) ProtoMessage()    {}
func (*UserAuthInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce91c7f1b4618f2e, []int{0}
}

func (m *UserAuthInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthInner.Unmarshal(m, b)
}
func (m *UserAuthInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthInner.Marshal(b, m, deterministic)
}
func (m *UserAuthInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthInner.Merge(m, src)
}
func (m *UserAuthInner) XXX_Size() int {
	return xxx_messageInfo_UserAuthInner.Size(m)
}
func (m *UserAuthInner) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthInner.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthInner proto.InternalMessageInfo

const Default_UserAuthInner_AuthType uint32 = 1

func (m *UserAuthInner) GetAuthType() uint32 {
	if m != nil && m.AuthType != nil {
		return *m.AuthType
	}
	return Default_UserAuthInner_AuthType
}

func (m *UserAuthInner) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *UserAuthInner) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *UserAuthInner) GetTimestamp() string {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return ""
}

func (m *UserAuthInner) GetDevice() uint32 {
	if m != nil && m.Device != nil {
		return *m.Device
	}
	return 0
}

func (m *UserAuthInner) GetSig() string {
	if m != nil && m.Sig != nil {
		return *m.Sig
	}
	return ""
}

func (m *UserAuthInner) GetSdkVersion() string {
	if m != nil && m.SdkVersion != nil {
		return *m.SdkVersion
	}
	return ""
}

func (m *UserAuthInner) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *UserAuthInner) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *UserAuthInner) GetNetwork() uint32 {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return 0
}

func (m *UserAuthInner) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func (m *UserAuthInner) GetBundleid() string {
	if m != nil && m.Bundleid != nil {
		return *m.Bundleid
	}
	return ""
}

func (m *UserAuthInner) GetSubDevice() string {
	if m != nil && m.SubDevice != nil {
		return *m.SubDevice
	}
	return ""
}

func (m *UserAuthInner) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *UserAuthInner) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*UserAuthInner)(nil), "UserAuthInner")
}

func init() { proto.RegisterFile("UserAuth.proto", fileDescriptor_ce91c7f1b4618f2e) }

var fileDescriptor_ce91c7f1b4618f2e = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xbb, 0x4e, 0xec, 0x30,
	0x10, 0x86, 0x95, 0xcd, 0x5e, 0xe7, 0x9c, 0x5d, 0x90, 0x85, 0xd0, 0x08, 0x01, 0x8a, 0xa8, 0x52,
	0x21, 0xd1, 0xd2, 0x81, 0x28, 0x48, 0x43, 0x11, 0x01, 0xbd, 0x17, 0x8f, 0xb2, 0xd6, 0x6e, 0x1c,
	0xcb, 0x17, 0x22, 0x5e, 0x81, 0xa7, 0x46, 0xb6, 0x37, 0x81, 0x6e, 0xbe, 0xef, 0xcf, 0x64, 0xf2,
	0x07, 0x36, 0x6f, 0x96, 0xcc, 0x83, 0x77, 0xbb, 0x5b, 0x6d, 0x3a, 0xd7, 0xdd, 0x7c, 0xe7, 0xb0,
	0x1e, 0x54, 0xa5, 0x14, 0x19, 0x76, 0x05, 0x4b, 0xee, 0xdd, 0xee, 0xf5, 0x4b, 0x13, 0x66, 0x45,
	0x56, 0xae, 0xef, 0xb3, 0xbb, 0x7a, 0x54, 0xec, 0x0c, 0x66, 0x5c, 0xeb, 0x4a, 0xe0, 0xa4, 0xc8,
	0xca, 0x55, 0x9d, 0x80, 0x5d, 0xc0, 0xd2, 0x5b, 0x32, 0x2f, 0xbc, 0x25, 0xcc, 0x63, 0x30, 0x32,
	0xbb, 0x84, 0x95, 0x93, 0x2d, 0x59, 0xc7, 0x5b, 0x8d, 0xd3, 0x18, 0xfe, 0x0a, 0x76, 0x0e, 0x73,
	0x41, 0x9f, 0xf2, 0x83, 0x70, 0x16, 0x8e, 0xd5, 0x47, 0x62, 0xa7, 0x90, 0x5b, 0xd9, 0xe0, 0x3c,
	0x3e, 0x1f, 0x46, 0x76, 0x0d, 0x60, 0xc5, 0xfe, 0x9d, 0x8c, 0x95, 0x9d, 0xc2, 0x45, 0x0c, 0xfe,
	0x18, 0xc6, 0x60, 0x2a, 0x5b, 0x92, 0xb8, 0x8c, 0x49, 0x9c, 0x83, 0x6b, 0x3b, 0x41, 0xb8, 0x8a,
	0xef, 0x8e, 0x33, 0x43, 0x58, 0x28, 0x72, 0x7d, 0x67, 0xf6, 0x08, 0x51, 0x0f, 0x18, 0x6e, 0xea,
	0x5e, 0xe0, 0xbf, 0x74, 0x53, 0xf7, 0xb1, 0xd7, 0xd6, 0x2b, 0x71, 0x20, 0x29, 0xf0, 0x7f, 0xea,
	0x35, 0x70, 0xe8, 0x65, 0xfd, 0xf6, 0x29, 0x7d, 0xfc, 0x3a, 0xf5, 0x1a, 0x45, 0xd8, 0x3c, 0x70,
	0xd5, 0x78, 0xde, 0x10, 0x6e, 0xd2, 0xe6, 0xc0, 0xa1, 0x73, 0xf8, 0x3b, 0x95, 0xc0, 0x93, 0x22,
	0x2b, 0xa7, 0xf5, 0x91, 0x1e, 0x27, 0xcf, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xd2,
	0x7d, 0x93, 0xa1, 0x01, 0x00, 0x00,
}
