// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AssignGroupAdmin.proto

package AssignGroupAdmin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssignGroupAdminInner struct {
	Owner                *uint64  `protobuf:"varint,1,opt,name=owner" json:"owner,omitempty"`
	MemberId             *uint64  `protobuf:"varint,2,req,name=memberId" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssignGroupAdminInner) Reset()         { *m = AssignGroupAdminInner{} }
func (m *AssignGroupAdminInner) String() string { return proto.CompactTextString(m) }
func (*AssignGroupAdminInner) ProtoMessage()    {}
func (*AssignGroupAdminInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_c944a53216d6a5ff, []int{0}
}

func (m *AssignGroupAdminInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssignGroupAdminInner.Unmarshal(m, b)
}
func (m *AssignGroupAdminInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssignGroupAdminInner.Marshal(b, m, deterministic)
}
func (m *AssignGroupAdminInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssignGroupAdminInner.Merge(m, src)
}
func (m *AssignGroupAdminInner) XXX_Size() int {
	return xxx_messageInfo_AssignGroupAdminInner.Size(m)
}
func (m *AssignGroupAdminInner) XXX_DiscardUnknown() {
	xxx_messageInfo_AssignGroupAdminInner.DiscardUnknown(m)
}

var xxx_messageInfo_AssignGroupAdminInner proto.InternalMessageInfo

func (m *AssignGroupAdminInner) GetOwner() uint64 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *AssignGroupAdminInner) GetMemberId() uint64 {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return 0
}

func init() {
	proto.RegisterType((*AssignGroupAdminInner)(nil), "AssignGroupAdminInner")
}

func init() { proto.RegisterFile("AssignGroupAdmin.proto", fileDescriptor_c944a53216d6a5ff) }

var fileDescriptor_c944a53216d6a5ff = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x73, 0x2c, 0x2e, 0xce,
	0x4c, 0xcf, 0x73, 0x2f, 0xca, 0x2f, 0x2d, 0x70, 0x4c, 0xc9, 0xcd, 0xcc, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0xf2, 0xe4, 0x12, 0x45, 0x97, 0xf1, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x12, 0xe1,
	0x62, 0xcd, 0x2f, 0xcf, 0x4b, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0x70, 0x84,
	0xa4, 0xb8, 0x38, 0x72, 0x53, 0x73, 0x93, 0x52, 0x8b, 0x3c, 0x53, 0x24, 0x98, 0x14, 0x98, 0x34,
	0x58, 0x82, 0xe0, 0x7c, 0x27, 0x26, 0x0f, 0x66, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x62,
	0x05, 0x8e, 0x67, 0x00, 0x00, 0x00,
}
