// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ConfirmInviteJoinGroup.proto

package ConfirmInviteJoinGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmInviteJoinGroupInner struct {
	GroupId              *uint64  `protobuf:"varint,1,req,name=groupId" json:"groupId,omitempty"`
	Invitor              *uint64  `protobuf:"varint,2,opt,name=invitor" json:"invitor,omitempty"`
	Confirm              *uint32  `protobuf:"varint,3,opt,name=confirm" json:"confirm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmInviteJoinGroupInner) Reset()         { *m = ConfirmInviteJoinGroupInner{} }
func (m *ConfirmInviteJoinGroupInner) String() string { return proto.CompactTextString(m) }
func (*ConfirmInviteJoinGroupInner) ProtoMessage()    {}
func (*ConfirmInviteJoinGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_5217623c9aaa5e27, []int{0}
}

func (m *ConfirmInviteJoinGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmInviteJoinGroupInner.Unmarshal(m, b)
}
func (m *ConfirmInviteJoinGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmInviteJoinGroupInner.Marshal(b, m, deterministic)
}
func (m *ConfirmInviteJoinGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmInviteJoinGroupInner.Merge(m, src)
}
func (m *ConfirmInviteJoinGroupInner) XXX_Size() int {
	return xxx_messageInfo_ConfirmInviteJoinGroupInner.Size(m)
}
func (m *ConfirmInviteJoinGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmInviteJoinGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmInviteJoinGroupInner proto.InternalMessageInfo

func (m *ConfirmInviteJoinGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *ConfirmInviteJoinGroupInner) GetInvitor() uint64 {
	if m != nil && m.Invitor != nil {
		return *m.Invitor
	}
	return 0
}

func (m *ConfirmInviteJoinGroupInner) GetConfirm() uint32 {
	if m != nil && m.Confirm != nil {
		return *m.Confirm
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfirmInviteJoinGroupInner)(nil), "ConfirmInviteJoinGroupInner")
}

func init() { proto.RegisterFile("ConfirmInviteJoinGroup.proto", fileDescriptor_5217623c9aaa5e27) }

var fileDescriptor_5217623c9aaa5e27 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x71, 0xce, 0xcf, 0x4b,
	0xcb, 0x2c, 0xca, 0xf5, 0xcc, 0x2b, 0xcb, 0x2c, 0x49, 0xf5, 0xca, 0xcf, 0xcc, 0x73, 0x2f, 0xca,
	0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xca, 0xe6, 0x92, 0xc6, 0x2e, 0xef, 0x99,
	0x97, 0x97, 0x5a, 0x24, 0x24, 0xc1, 0xc5, 0x9e, 0x0e, 0xe6, 0xa5, 0x48, 0x30, 0x2a, 0x30, 0x69,
	0xb0, 0x04, 0xc1, 0xb8, 0x20, 0x99, 0x4c, 0x90, 0x8e, 0xfc, 0x22, 0x09, 0x26, 0x05, 0x46, 0x90,
	0x0c, 0x94, 0x0b, 0x92, 0x49, 0x86, 0x18, 0x29, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1b, 0x04, 0xe3,
	0x3a, 0xa9, 0x71, 0x29, 0x25, 0xe7, 0xe7, 0xea, 0x55, 0x96, 0xe6, 0x95, 0xe4, 0xe7, 0xa5, 0x57,
	0x94, 0xe6, 0xe9, 0xe5, 0xe4, 0xa7, 0x67, 0x26, 0xeb, 0x25, 0xe7, 0x17, 0xa5, 0x42, 0xdc, 0x93,
	0x54, 0x9a, 0xe6, 0xc1, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x30, 0x66, 0x4b, 0xb3, 0x00,
	0x00, 0x00,
}
