// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ConfirmJoinGroup.proto

package ConfirmJoinGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmJoinGroupInner struct {
	Acker                *uint64                         `protobuf:"varint,1,opt,name=acker" json:"acker,omitempty"`
	GroupId              *uint64                         `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	MemberId             *uint64                         `protobuf:"varint,3,opt,name=memberId" json:"memberId,omitempty"`
	Confirm              *uint32                         `protobuf:"varint,4,opt,name=confirm" json:"confirm,omitempty"`
	MemberIds            []*ConfirmJoinGroupInnerMembers `protobuf:"bytes,5,rep,name=memberIds" json:"memberIds,omitempty"`
	Ext                  *string                         `protobuf:"bytes,6,opt,name=ext" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ConfirmJoinGroupInner) Reset()         { *m = ConfirmJoinGroupInner{} }
func (m *ConfirmJoinGroupInner) String() string { return proto.CompactTextString(m) }
func (*ConfirmJoinGroupInner) ProtoMessage()    {}
func (*ConfirmJoinGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c54e3cdcfdd0377, []int{0}
}

func (m *ConfirmJoinGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmJoinGroupInner.Unmarshal(m, b)
}
func (m *ConfirmJoinGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmJoinGroupInner.Marshal(b, m, deterministic)
}
func (m *ConfirmJoinGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmJoinGroupInner.Merge(m, src)
}
func (m *ConfirmJoinGroupInner) XXX_Size() int {
	return xxx_messageInfo_ConfirmJoinGroupInner.Size(m)
}
func (m *ConfirmJoinGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmJoinGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmJoinGroupInner proto.InternalMessageInfo

func (m *ConfirmJoinGroupInner) GetAcker() uint64 {
	if m != nil && m.Acker != nil {
		return *m.Acker
	}
	return 0
}

func (m *ConfirmJoinGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *ConfirmJoinGroupInner) GetMemberId() uint64 {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return 0
}

func (m *ConfirmJoinGroupInner) GetConfirm() uint32 {
	if m != nil && m.Confirm != nil {
		return *m.Confirm
	}
	return 0
}

func (m *ConfirmJoinGroupInner) GetMemberIds() []*ConfirmJoinGroupInnerMembers {
	if m != nil {
		return m.MemberIds
	}
	return nil
}

func (m *ConfirmJoinGroupInner) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

type ConfirmJoinGroupInnerMembers struct {
	MemberId             *uint64  `protobuf:"varint,1,opt,name=memberId" json:"memberId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmJoinGroupInnerMembers) Reset()         { *m = ConfirmJoinGroupInnerMembers{} }
func (m *ConfirmJoinGroupInnerMembers) String() string { return proto.CompactTextString(m) }
func (*ConfirmJoinGroupInnerMembers) ProtoMessage()    {}
func (*ConfirmJoinGroupInnerMembers) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c54e3cdcfdd0377, []int{1}
}

func (m *ConfirmJoinGroupInnerMembers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmJoinGroupInnerMembers.Unmarshal(m, b)
}
func (m *ConfirmJoinGroupInnerMembers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmJoinGroupInnerMembers.Marshal(b, m, deterministic)
}
func (m *ConfirmJoinGroupInnerMembers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmJoinGroupInnerMembers.Merge(m, src)
}
func (m *ConfirmJoinGroupInnerMembers) XXX_Size() int {
	return xxx_messageInfo_ConfirmJoinGroupInnerMembers.Size(m)
}
func (m *ConfirmJoinGroupInnerMembers) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmJoinGroupInnerMembers.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmJoinGroupInnerMembers proto.InternalMessageInfo

func (m *ConfirmJoinGroupInnerMembers) GetMemberId() uint64 {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return 0
}

func init() {
	proto.RegisterType((*ConfirmJoinGroupInner)(nil), "ConfirmJoinGroupInner")
	proto.RegisterType((*ConfirmJoinGroupInnerMembers)(nil), "ConfirmJoinGroupInnerMembers")
}

func init() { proto.RegisterFile("ConfirmJoinGroup.proto", fileDescriptor_1c54e3cdcfdd0377) }

var fileDescriptor_1c54e3cdcfdd0377 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x73, 0xce, 0xcf, 0x4b,
	0xcb, 0x2c, 0xca, 0xf5, 0xca, 0xcf, 0xcc, 0x73, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x3a, 0xc3, 0xc8, 0x25, 0x8a, 0x2e, 0xe5, 0x99, 0x97, 0x97, 0x5a, 0x24, 0x24,
	0xc2, 0xc5, 0x9a, 0x98, 0x9c, 0x9d, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe1,
	0x08, 0x49, 0x70, 0xb1, 0xa7, 0x83, 0xd5, 0xa4, 0x48, 0x30, 0x29, 0x30, 0x69, 0xb0, 0x04, 0xc1,
	0xb8, 0x42, 0x52, 0x5c, 0x1c, 0xb9, 0xa9, 0xb9, 0x49, 0xa9, 0x45, 0x9e, 0x29, 0x12, 0xcc, 0x60,
	0x2d, 0x70, 0x3e, 0x48, 0x57, 0x32, 0xc4, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xde, 0x20, 0x18,
	0x57, 0xc8, 0x9a, 0x8b, 0x13, 0xa6, 0xaa, 0x58, 0x82, 0x55, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x56,
	0x0f, 0xab, 0x83, 0x7c, 0xc1, 0xca, 0x8a, 0x83, 0x10, 0xea, 0x85, 0x04, 0xb8, 0x98, 0x53, 0x2b,
	0x4a, 0x24, 0xd8, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x25, 0x2b, 0x2e, 0x19, 0x7c, 0x9a,
	0x51, 0x1c, 0xc9, 0x88, 0xea, 0x48, 0x27, 0x35, 0x2e, 0xa5, 0xe4, 0xfc, 0x5c, 0xbd, 0xca, 0xd2,
	0xbc, 0x92, 0xfc, 0xbc, 0xf4, 0x8a, 0xd2, 0x3c, 0xbd, 0x9c, 0xfc, 0xf4, 0xcc, 0x64, 0xbd, 0xe4,
	0xfc, 0xa2, 0x54, 0x48, 0x68, 0x25, 0x95, 0xa6, 0x79, 0x30, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x27, 0x09, 0x59, 0x7c, 0x4b, 0x01, 0x00, 0x00,
}
