// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CreateGroup.proto

package CreateGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGroupInner struct {
	Creator              *uint64  `protobuf:"varint,1,opt,name=creator" json:"creator,omitempty"`
	GroupName            *string  `protobuf:"bytes,2,opt,name=groupName" json:"groupName,omitempty"`
	Type                 *uint32  `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Province             *string  `protobuf:"bytes,4,opt,name=province" json:"province,omitempty"`
	City                 *string  `protobuf:"bytes,5,opt,name=city" json:"city,omitempty"`
	Scope                *uint32  `protobuf:"varint,6,opt,name=scope" json:"scope,omitempty"`
	Declared             *string  `protobuf:"bytes,7,opt,name=declared" json:"declared,omitempty"`
	Permission           *uint32  `protobuf:"varint,8,opt,name=permission" json:"permission,omitempty"`
	Mode                 *uint32  `protobuf:"varint,9,opt,name=mode" json:"mode,omitempty"`
	GroupDomain          *string  `protobuf:"bytes,10,opt,name=groupDomain" json:"groupDomain,omitempty"`
	Target               *uint32  `protobuf:"varint,11,opt,name=target" json:"target,omitempty"`
	IsForbid             *uint32  `protobuf:"varint,12,opt,name=isForbid" json:"isForbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupInner) Reset()         { *m = CreateGroupInner{} }
func (m *CreateGroupInner) String() string { return proto.CompactTextString(m) }
func (*CreateGroupInner) ProtoMessage()    {}
func (*CreateGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f05bb26ae27f0b1, []int{0}
}

func (m *CreateGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupInner.Unmarshal(m, b)
}
func (m *CreateGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupInner.Marshal(b, m, deterministic)
}
func (m *CreateGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupInner.Merge(m, src)
}
func (m *CreateGroupInner) XXX_Size() int {
	return xxx_messageInfo_CreateGroupInner.Size(m)
}
func (m *CreateGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupInner proto.InternalMessageInfo

func (m *CreateGroupInner) GetCreator() uint64 {
	if m != nil && m.Creator != nil {
		return *m.Creator
	}
	return 0
}

func (m *CreateGroupInner) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *CreateGroupInner) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CreateGroupInner) GetProvince() string {
	if m != nil && m.Province != nil {
		return *m.Province
	}
	return ""
}

func (m *CreateGroupInner) GetCity() string {
	if m != nil && m.City != nil {
		return *m.City
	}
	return ""
}

func (m *CreateGroupInner) GetScope() uint32 {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return 0
}

func (m *CreateGroupInner) GetDeclared() string {
	if m != nil && m.Declared != nil {
		return *m.Declared
	}
	return ""
}

func (m *CreateGroupInner) GetPermission() uint32 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *CreateGroupInner) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *CreateGroupInner) GetGroupDomain() string {
	if m != nil && m.GroupDomain != nil {
		return *m.GroupDomain
	}
	return ""
}

func (m *CreateGroupInner) GetTarget() uint32 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func (m *CreateGroupInner) GetIsForbid() uint32 {
	if m != nil && m.IsForbid != nil {
		return *m.IsForbid
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateGroupInner)(nil), "CreateGroupInner")
}

func init() { proto.RegisterFile("CreateGroup.proto", fileDescriptor_4f05bb26ae27f0b1) }

var fileDescriptor_4f05bb26ae27f0b1 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xdb, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0xb7, 0x7b, 0xe8, 0xac, 0x82, 0x06, 0x91, 0x41, 0x44, 0x8a, 0x57, 0xbd, 0xf2,
	0x21, 0x54, 0x3c, 0xdc, 0x78, 0xd1, 0x37, 0x88, 0xe9, 0xb0, 0x04, 0x6c, 0x26, 0x4c, 0xa3, 0xb0,
	0xaf, 0xe8, 0x53, 0x49, 0xa6, 0xee, 0x6e, 0xef, 0xe6, 0xfb, 0x32, 0xf3, 0xe7, 0x87, 0xcb, 0x27,
	0x21, 0x9b, 0xe8, 0x55, 0xf8, 0x3b, 0x3e, 0x44, 0xe1, 0xc4, 0xf7, 0xbf, 0x25, 0x5c, 0xcc, 0xec,
	0x7b, 0x08, 0x24, 0x06, 0x61, 0xed, 0xb2, 0x63, 0xc1, 0xa2, 0x29, 0xda, 0xaa, 0x3b, 0xa0, 0xb9,
	0x85, 0x7a, 0x97, 0xf7, 0x3e, 0xec, 0x40, 0x58, 0x36, 0x45, 0x5b, 0x77, 0x27, 0x61, 0x0c, 0x54,
	0x69, 0x1f, 0x09, 0x17, 0x4d, 0xd1, 0x9e, 0x77, 0x3a, 0x9b, 0x1b, 0xd8, 0x44, 0xe1, 0x1f, 0x1f,
	0x1c, 0x61, 0xa5, 0x07, 0x47, 0xce, 0xfb, 0xce, 0xa7, 0x3d, 0x2e, 0xd5, 0xeb, 0x6c, 0xae, 0x60,
	0x39, 0x3a, 0x8e, 0x84, 0x2b, 0x0d, 0x99, 0x20, 0xa7, 0xf4, 0xe4, 0xbe, 0xac, 0x50, 0x8f, 0xeb,
	0x29, 0xe5, 0xc0, 0xe6, 0x0e, 0x20, 0x92, 0x0c, 0x7e, 0x1c, 0x3d, 0x07, 0xdc, 0xe8, 0xd9, 0xcc,
	0xe4, 0x5f, 0x06, 0xee, 0x09, 0xeb, 0xa9, 0x55, 0x9e, 0x4d, 0x03, 0x5b, 0xad, 0xfd, 0xcc, 0x83,
	0xf5, 0x01, 0x41, 0x23, 0xe7, 0xca, 0x5c, 0xc3, 0x2a, 0x59, 0xd9, 0x51, 0xc2, 0xad, 0xde, 0xfd,
	0x53, 0x6e, 0xe2, 0xc7, 0x17, 0x96, 0x4f, 0xdf, 0xe3, 0x99, 0xbe, 0x1c, 0xf9, 0xb1, 0x7c, 0x5b,
	0xfc, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x4d, 0xd1, 0x1a, 0x64, 0x01, 0x00, 0x00,
}
