// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CreateGroupResp.proto

package CreateGroupResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGroupRespInner struct {
	GroupId              *uint64  `protobuf:"varint,1,req,name=groupId" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRespInner) Reset()         { *m = CreateGroupRespInner{} }
func (m *CreateGroupRespInner) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRespInner) ProtoMessage()    {}
func (*CreateGroupRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f36d1b6f4c133726, []int{0}
}

func (m *CreateGroupRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRespInner.Unmarshal(m, b)
}
func (m *CreateGroupRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRespInner.Marshal(b, m, deterministic)
}
func (m *CreateGroupRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRespInner.Merge(m, src)
}
func (m *CreateGroupRespInner) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRespInner.Size(m)
}
func (m *CreateGroupRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRespInner proto.InternalMessageInfo

func (m *CreateGroupRespInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateGroupRespInner)(nil), "CreateGroupRespInner")
}

func init() { proto.RegisterFile("CreateGroupResp.proto", fileDescriptor_f36d1b6f4c133726) }

var fileDescriptor_f36d1b6f4c133726 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x75, 0x2e, 0x4a, 0x4d,
	0x2c, 0x49, 0x75, 0x2f, 0xca, 0x2f, 0x2d, 0x08, 0x4a, 0x2d, 0x2e, 0xd0, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x57, 0x32, 0xe0, 0x12, 0x41, 0x93, 0xf0, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x92, 0xe0, 0x62,
	0x4f, 0x07, 0x89, 0x78, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x04, 0xc1, 0xb8, 0x4e, 0x4c,
	0x1e, 0xcc, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x73, 0x75, 0x3a, 0x4d, 0x00, 0x00, 0x00,
}
