// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeleteGroupMember.proto

package DeleteGroupMember

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteGroupMemberInner struct {
	Deletor              *uint64  `protobuf:"varint,1,opt,name=deletor" json:"deletor,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	Member               []string `protobuf:"bytes,3,rep,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupMemberInner) Reset()         { *m = DeleteGroupMemberInner{} }
func (m *DeleteGroupMemberInner) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupMemberInner) ProtoMessage()    {}
func (*DeleteGroupMemberInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c60931e854afa7f, []int{0}
}

func (m *DeleteGroupMemberInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupMemberInner.Unmarshal(m, b)
}
func (m *DeleteGroupMemberInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupMemberInner.Marshal(b, m, deterministic)
}
func (m *DeleteGroupMemberInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupMemberInner.Merge(m, src)
}
func (m *DeleteGroupMemberInner) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupMemberInner.Size(m)
}
func (m *DeleteGroupMemberInner) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupMemberInner.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupMemberInner proto.InternalMessageInfo

func (m *DeleteGroupMemberInner) GetDeletor() uint64 {
	if m != nil && m.Deletor != nil {
		return *m.Deletor
	}
	return 0
}

func (m *DeleteGroupMemberInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *DeleteGroupMemberInner) GetMember() []string {
	if m != nil {
		return m.Member
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteGroupMemberInner)(nil), "DeleteGroupMemberInner")
}

func init() { proto.RegisterFile("DeleteGroupMember.proto", fileDescriptor_3c60931e854afa7f) }

var fileDescriptor_3c60931e854afa7f = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x77, 0x49, 0xcd, 0x49,
	0x2d, 0x49, 0x75, 0x2f, 0xca, 0x2f, 0x2d, 0xf0, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0xd2, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe1, 0x12, 0xc3, 0x90, 0xf2, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x92,
	0xe0, 0x62, 0x4f, 0x01, 0xc9, 0xe4, 0x17, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0xc1, 0xb8,
	0x20, 0x99, 0x74, 0x90, 0x6a, 0xcf, 0x14, 0x09, 0x26, 0x05, 0x26, 0x90, 0x0c, 0x94, 0x2b, 0x24,
	0xc6, 0xc5, 0x96, 0x0b, 0x36, 0x42, 0x82, 0x59, 0x81, 0x59, 0x83, 0x33, 0x08, 0xca, 0x73, 0x62,
	0xf2, 0x60, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xdb, 0xa8, 0x21, 0x83, 0x00, 0x00, 0x00,
}
