// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DismissGroup.proto

package DismissGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DismissGroupInner struct {
	Operator             *uint64  `protobuf:"varint,1,opt,name=operator" json:"operator,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	Target               *uint32  `protobuf:"varint,3,opt,name=target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DismissGroupInner) Reset()         { *m = DismissGroupInner{} }
func (m *DismissGroupInner) String() string { return proto.CompactTextString(m) }
func (*DismissGroupInner) ProtoMessage()    {}
func (*DismissGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_be81bb096e4c767f, []int{0}
}

func (m *DismissGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DismissGroupInner.Unmarshal(m, b)
}
func (m *DismissGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DismissGroupInner.Marshal(b, m, deterministic)
}
func (m *DismissGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DismissGroupInner.Merge(m, src)
}
func (m *DismissGroupInner) XXX_Size() int {
	return xxx_messageInfo_DismissGroupInner.Size(m)
}
func (m *DismissGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_DismissGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_DismissGroupInner proto.InternalMessageInfo

func (m *DismissGroupInner) GetOperator() uint64 {
	if m != nil && m.Operator != nil {
		return *m.Operator
	}
	return 0
}

func (m *DismissGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *DismissGroupInner) GetTarget() uint32 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func init() {
	proto.RegisterType((*DismissGroupInner)(nil), "DismissGroupInner")
}

func init() { proto.RegisterFile("DismissGroup.proto", fileDescriptor_be81bb096e4c767f) }

var fileDescriptor_be81bb096e4c767f = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x72, 0xc9, 0x2c, 0xce,
	0xcd, 0x2c, 0x2e, 0x76, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a,
	0xe4, 0x12, 0x44, 0x16, 0xf5, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x92, 0xe2, 0xe2, 0xc8, 0x2f, 0x48,
	0x2d, 0x4a, 0x2c, 0xc9, 0x2f, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0xf3, 0x85, 0x24,
	0xb8, 0xd8, 0xd3, 0xc1, 0x2a, 0x53, 0x24, 0x98, 0x14, 0x98, 0x34, 0x58, 0x82, 0x60, 0x5c, 0x21,
	0x31, 0x2e, 0xb6, 0x92, 0xc4, 0xa2, 0xf4, 0xd4, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xde, 0x20,
	0x28, 0xcf, 0x89, 0xc9, 0x83, 0x19, 0x10, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xf6, 0xbc, 0xe4, 0x7b,
	0x00, 0x00, 0x00,
}
