// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetGroupMembersResp.proto

package GetGroupMembersResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGroupMembersRespInner struct {
	GroupId              *uint64             `protobuf:"varint,1,req,name=groupId" json:"groupId,omitempty"`
	Members              []*GroupMemberInner `protobuf:"bytes,2,rep,name=members" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetGroupMembersRespInner) Reset()         { *m = GetGroupMembersRespInner{} }
func (m *GetGroupMembersRespInner) String() string { return proto.CompactTextString(m) }
func (*GetGroupMembersRespInner) ProtoMessage()    {}
func (*GetGroupMembersRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7b9dbca91288b37, []int{0}
}

func (m *GetGroupMembersRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupMembersRespInner.Unmarshal(m, b)
}
func (m *GetGroupMembersRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupMembersRespInner.Marshal(b, m, deterministic)
}
func (m *GetGroupMembersRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupMembersRespInner.Merge(m, src)
}
func (m *GetGroupMembersRespInner) XXX_Size() int {
	return xxx_messageInfo_GetGroupMembersRespInner.Size(m)
}
func (m *GetGroupMembersRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupMembersRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupMembersRespInner proto.InternalMessageInfo

func (m *GetGroupMembersRespInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GetGroupMembersRespInner) GetMembers() []*GroupMemberInner {
	if m != nil {
		return m.Members
	}
	return nil
}

type GroupMemberInner struct {
	Useracc              *string  `protobuf:"bytes,1,opt,name=useracc" json:"useracc,omitempty"`
	NickName             *string  `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	SpeakState           *uint32  `protobuf:"varint,3,opt,name=speakState,def=1" json:"speakState,omitempty"`
	Role                 *uint32  `protobuf:"varint,4,opt,name=role" json:"role,omitempty"`
	Sex                  *uint32  `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMemberInner) Reset()         { *m = GroupMemberInner{} }
func (m *GroupMemberInner) String() string { return proto.CompactTextString(m) }
func (*GroupMemberInner) ProtoMessage()    {}
func (*GroupMemberInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7b9dbca91288b37, []int{1}
}

func (m *GroupMemberInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMemberInner.Unmarshal(m, b)
}
func (m *GroupMemberInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMemberInner.Marshal(b, m, deterministic)
}
func (m *GroupMemberInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMemberInner.Merge(m, src)
}
func (m *GroupMemberInner) XXX_Size() int {
	return xxx_messageInfo_GroupMemberInner.Size(m)
}
func (m *GroupMemberInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMemberInner.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMemberInner proto.InternalMessageInfo

const Default_GroupMemberInner_SpeakState uint32 = 1

func (m *GroupMemberInner) GetUseracc() string {
	if m != nil && m.Useracc != nil {
		return *m.Useracc
	}
	return ""
}

func (m *GroupMemberInner) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *GroupMemberInner) GetSpeakState() uint32 {
	if m != nil && m.SpeakState != nil {
		return *m.SpeakState
	}
	return Default_GroupMemberInner_SpeakState
}

func (m *GroupMemberInner) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *GroupMemberInner) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*GetGroupMembersRespInner)(nil), "GetGroupMembersRespInner")
	proto.RegisterType((*GroupMemberInner)(nil), "GroupMemberInner")
}

func init() { proto.RegisterFile("GetGroupMembersResp.proto", fileDescriptor_b7b9dbca91288b37) }

var fileDescriptor_b7b9dbca91288b37 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8c, 0xb1, 0x4a, 0xc6, 0x30,
	0x14, 0x85, 0x49, 0x52, 0xa9, 0x5e, 0x11, 0x6a, 0xa6, 0xab, 0x53, 0xec, 0x14, 0x10, 0x0a, 0x3a,
	0x3a, 0xba, 0xd4, 0x0e, 0x3a, 0xc4, 0x27, 0x88, 0xf5, 0x22, 0x52, 0xdb, 0x84, 0x24, 0x05, 0x5f,
	0xc3, 0x37, 0x96, 0x44, 0x2a, 0xe5, 0xe7, 0xdf, 0xee, 0x77, 0xbe, 0x73, 0x0f, 0x5c, 0xf5, 0x94,
	0xfa, 0xe0, 0x56, 0xff, 0x4c, 0xf3, 0x1b, 0x85, 0x68, 0x28, 0xfa, 0xce, 0x07, 0x97, 0x5c, 0x6b,
	0x01, 0x8f, 0xc8, 0x61, 0x59, 0x28, 0x48, 0x84, 0xfa, 0x23, 0x8b, 0xe1, 0x1d, 0x99, 0xe2, 0xba,
	0x32, 0x1b, 0xca, 0x5b, 0xa8, 0xe7, 0xbf, 0x36, 0x72, 0x25, 0xf4, 0xf9, 0xfd, 0x65, 0xb7, 0x9b,
	0x28, 0xdf, 0x66, 0x6b, 0xb4, 0x3f, 0x0c, 0x9a, 0x43, 0x9b, 0xb7, 0xd7, 0x48, 0xc1, 0x8e, 0x23,
	0x32, 0xc5, 0xf4, 0x99, 0xd9, 0x50, 0x5e, 0xc3, 0xe9, 0xf2, 0x39, 0x4e, 0x2f, 0x76, 0x26, 0xe4,
	0x45, 0xfd, 0xb3, 0xbc, 0x01, 0x88, 0x9e, 0xec, 0xf4, 0x9a, 0x6c, 0x22, 0x14, 0x8a, 0xe9, 0x8b,
	0x07, 0x76, 0x67, 0x76, 0xa1, 0x94, 0x50, 0x05, 0xf7, 0x45, 0x58, 0x65, 0x69, 0xca, 0x2d, 0x1b,
	0x10, 0x91, 0xbe, 0xf1, 0xa4, 0x44, 0xf9, 0x7c, 0xe4, 0x4f, 0xe2, 0x37, 0x00, 0x00, 0xff, 0xff,
	0x94, 0xa1, 0xfe, 0xc9, 0x16, 0x01, 0x00, 0x00,
}
