// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetGroupDetail.proto

package GetGroupDetail

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetGroupDetailInner struct {
	Asker                *uint64  `protobuf:"varint,1,opt,name=asker" json:"asker,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupDetailInner) Reset()         { *m = GetGroupDetailInner{} }
func (m *GetGroupDetailInner) String() string { return proto.CompactTextString(m) }
func (*GetGroupDetailInner) ProtoMessage()    {}
func (*GetGroupDetailInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_32e7217a549321fc, []int{0}
}

func (m *GetGroupDetailInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupDetailInner.Unmarshal(m, b)
}
func (m *GetGroupDetailInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupDetailInner.Marshal(b, m, deterministic)
}
func (m *GetGroupDetailInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupDetailInner.Merge(m, src)
}
func (m *GetGroupDetailInner) XXX_Size() int {
	return xxx_messageInfo_GetGroupDetailInner.Size(m)
}
func (m *GetGroupDetailInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupDetailInner.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupDetailInner proto.InternalMessageInfo

func (m *GetGroupDetailInner) GetAsker() uint64 {
	if m != nil && m.Asker != nil {
		return *m.Asker
	}
	return 0
}

func (m *GetGroupDetailInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetGroupDetailInner)(nil), "GetGroupDetailInner")
}

func init() { proto.RegisterFile("GetGroupDetail.proto", fileDescriptor_32e7217a549321fc) }

var fileDescriptor_32e7217a549321fc = []byte{
	// 97 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0x4f, 0x2d, 0x71,
	0x2f, 0xca, 0x2f, 0x2d, 0x70, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0x72, 0xe5, 0x12, 0x46, 0x15, 0xf7, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0x4d,
	0x2c, 0xce, 0x4e, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x82, 0x70, 0x84, 0x24, 0xb8,
	0xd8, 0xd3, 0x41, 0x2a, 0x3d, 0x53, 0x24, 0x98, 0x14, 0x98, 0x34, 0x58, 0x82, 0x60, 0x5c, 0x27,
	0x26, 0x0f, 0x66, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x17, 0x50, 0x2d, 0x61, 0x00, 0x00,
	0x00,
}
