// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetOwnerGroupsResp.proto

package GetOwnerGroupsResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOwnerGroupsRespInner struct {
	Groups               []*GroupSimpleInfo `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetOwnerGroupsRespInner) Reset()         { *m = GetOwnerGroupsRespInner{} }
func (m *GetOwnerGroupsRespInner) String() string { return proto.CompactTextString(m) }
func (*GetOwnerGroupsRespInner) ProtoMessage()    {}
func (*GetOwnerGroupsRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_724528edb8196825, []int{0}
}

func (m *GetOwnerGroupsRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerGroupsRespInner.Unmarshal(m, b)
}
func (m *GetOwnerGroupsRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerGroupsRespInner.Marshal(b, m, deterministic)
}
func (m *GetOwnerGroupsRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerGroupsRespInner.Merge(m, src)
}
func (m *GetOwnerGroupsRespInner) XXX_Size() int {
	return xxx_messageInfo_GetOwnerGroupsRespInner.Size(m)
}
func (m *GetOwnerGroupsRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerGroupsRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerGroupsRespInner proto.InternalMessageInfo

func (m *GetOwnerGroupsRespInner) GetGroups() []*GroupSimpleInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

type GroupSimpleInfo struct {
	GroupId              *uint64                             `protobuf:"varint,1,opt,name=groupId" json:"groupId,omitempty"`
	Name                 *string                             `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner                *uint64                             `protobuf:"varint,3,opt,name=owner" json:"owner,omitempty"`
	Permission           *uint32                             `protobuf:"varint,4,opt,name=permission" json:"permission,omitempty"`
	IsNotice             *uint32                             `protobuf:"varint,5,opt,name=isNotice" json:"isNotice,omitempty"`
	MemberCount          *uint32                             `protobuf:"varint,6,opt,name=memberCount" json:"memberCount,omitempty"`
	Scope                *uint32                             `protobuf:"varint,7,opt,name=scope" json:"scope,omitempty"`
	DateCreated          *string                             `protobuf:"bytes,8,opt,name=dateCreated" json:"dateCreated,omitempty"`
	Target               *uint32                             `protobuf:"varint,9,opt,name=target" json:"target,omitempty"`
	Members              []*GroupSimpleInfo_GroupMemberInner `protobuf:"bytes,10,rep,name=members" json:"members,omitempty"`
	Type                 *uint32                             `protobuf:"varint,11,opt,name=type" json:"type,omitempty"`
	GroupDomain          *string                             `protobuf:"bytes,12,opt,name=groupDomain" json:"groupDomain,omitempty"`
	IsForbid             *uint32                             `protobuf:"varint,13,opt,name=isForbid" json:"isForbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *GroupSimpleInfo) Reset()         { *m = GroupSimpleInfo{} }
func (m *GroupSimpleInfo) String() string { return proto.CompactTextString(m) }
func (*GroupSimpleInfo) ProtoMessage()    {}
func (*GroupSimpleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_724528edb8196825, []int{1}
}

func (m *GroupSimpleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSimpleInfo.Unmarshal(m, b)
}
func (m *GroupSimpleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSimpleInfo.Marshal(b, m, deterministic)
}
func (m *GroupSimpleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSimpleInfo.Merge(m, src)
}
func (m *GroupSimpleInfo) XXX_Size() int {
	return xxx_messageInfo_GroupSimpleInfo.Size(m)
}
func (m *GroupSimpleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSimpleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSimpleInfo proto.InternalMessageInfo

func (m *GroupSimpleInfo) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupSimpleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GroupSimpleInfo) GetOwner() uint64 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *GroupSimpleInfo) GetPermission() uint32 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *GroupSimpleInfo) GetIsNotice() uint32 {
	if m != nil && m.IsNotice != nil {
		return *m.IsNotice
	}
	return 0
}

func (m *GroupSimpleInfo) GetMemberCount() uint32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

func (m *GroupSimpleInfo) GetScope() uint32 {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return 0
}

func (m *GroupSimpleInfo) GetDateCreated() string {
	if m != nil && m.DateCreated != nil {
		return *m.DateCreated
	}
	return ""
}

func (m *GroupSimpleInfo) GetTarget() uint32 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func (m *GroupSimpleInfo) GetMembers() []*GroupSimpleInfo_GroupMemberInner {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *GroupSimpleInfo) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *GroupSimpleInfo) GetGroupDomain() string {
	if m != nil && m.GroupDomain != nil {
		return *m.GroupDomain
	}
	return ""
}

func (m *GroupSimpleInfo) GetIsForbid() uint32 {
	if m != nil && m.IsForbid != nil {
		return *m.IsForbid
	}
	return 0
}

type GroupSimpleInfo_GroupMemberInner struct {
	Member               *uint64  `protobuf:"varint,1,opt,name=member" json:"member,omitempty"`
	NickName             *string  `protobuf:"bytes,2,opt,name=nickName" json:"nickName,omitempty"`
	SpeakState           *uint32  `protobuf:"varint,3,opt,name=speakState,def=1" json:"speakState,omitempty"`
	Role                 *uint32  `protobuf:"varint,4,opt,name=role" json:"role,omitempty"`
	Sex                  *uint32  `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupSimpleInfo_GroupMemberInner) Reset()         { *m = GroupSimpleInfo_GroupMemberInner{} }
func (m *GroupSimpleInfo_GroupMemberInner) String() string { return proto.CompactTextString(m) }
func (*GroupSimpleInfo_GroupMemberInner) ProtoMessage()    {}
func (*GroupSimpleInfo_GroupMemberInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_724528edb8196825, []int{1, 0}
}

func (m *GroupSimpleInfo_GroupMemberInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSimpleInfo_GroupMemberInner.Unmarshal(m, b)
}
func (m *GroupSimpleInfo_GroupMemberInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSimpleInfo_GroupMemberInner.Marshal(b, m, deterministic)
}
func (m *GroupSimpleInfo_GroupMemberInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSimpleInfo_GroupMemberInner.Merge(m, src)
}
func (m *GroupSimpleInfo_GroupMemberInner) XXX_Size() int {
	return xxx_messageInfo_GroupSimpleInfo_GroupMemberInner.Size(m)
}
func (m *GroupSimpleInfo_GroupMemberInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSimpleInfo_GroupMemberInner.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSimpleInfo_GroupMemberInner proto.InternalMessageInfo

const Default_GroupSimpleInfo_GroupMemberInner_SpeakState uint32 = 1

func (m *GroupSimpleInfo_GroupMemberInner) GetMember() uint64 {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return 0
}

func (m *GroupSimpleInfo_GroupMemberInner) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *GroupSimpleInfo_GroupMemberInner) GetSpeakState() uint32 {
	if m != nil && m.SpeakState != nil {
		return *m.SpeakState
	}
	return Default_GroupSimpleInfo_GroupMemberInner_SpeakState
}

func (m *GroupSimpleInfo_GroupMemberInner) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *GroupSimpleInfo_GroupMemberInner) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*GetOwnerGroupsRespInner)(nil), "GetOwnerGroupsRespInner")
	proto.RegisterType((*GroupSimpleInfo)(nil), "GroupSimpleInfo")
	proto.RegisterType((*GroupSimpleInfo_GroupMemberInner)(nil), "GroupSimpleInfo.GroupMemberInner")
}

func init() { proto.RegisterFile("GetOwnerGroupsResp.proto", fileDescriptor_724528edb8196825) }

var fileDescriptor_724528edb8196825 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xcd, 0xce, 0x12, 0x41,
	0x10, 0xcc, 0xb2, 0xcb, 0x5f, 0x23, 0x91, 0x4c, 0x8c, 0x76, 0x38, 0x98, 0x85, 0xd3, 0x9e, 0x48,
	0xf4, 0xa8, 0x37, 0x31, 0x22, 0x07, 0x31, 0x59, 0x9e, 0x60, 0x61, 0x5b, 0x32, 0x81, 0x9d, 0x99,
	0xcc, 0x0c, 0x51, 0x9f, 0xc2, 0x97, 0xf0, 0x41, 0xbf, 0x4c, 0xcf, 0xc2, 0xb7, 0xe1, 0xbb, 0x75,
	0x55, 0xf5, 0x4f, 0xa5, 0x1a, 0x70, 0x43, 0xfe, 0xe7, 0x6f, 0x45, 0x76, 0x63, 0xf5, 0xd5, 0xb8,
	0x92, 0x9c, 0x59, 0x19, 0xab, 0xbd, 0x5e, 0xae, 0xe1, 0xdd, 0x4b, 0x6d, 0xab, 0x14, 0x59, 0x51,
	0xc0, 0xe0, 0xc4, 0x14, 0x26, 0x79, 0x5a, 0x4c, 0x3e, 0xce, 0x56, 0xdc, 0xb1, 0x97, 0x8d, 0xb9,
	0xd0, 0x56, 0xfd, 0xd2, 0x65, 0xab, 0x2f, 0xff, 0x67, 0xf0, 0xfa, 0x41, 0x13, 0x08, 0x43, 0x56,
	0xb7, 0x35, 0x26, 0x79, 0x52, 0x64, 0xe5, 0x0d, 0x0a, 0x01, 0x99, 0xaa, 0x1a, 0xc2, 0x5e, 0x9e,
	0x14, 0xe3, 0x92, 0x6b, 0xf1, 0x06, 0xfa, 0x3a, 0x78, 0xc0, 0x94, 0x7b, 0x23, 0x10, 0xef, 0x01,
	0x0c, 0xd9, 0x46, 0x3a, 0x27, 0xb5, 0xc2, 0x2c, 0x4f, 0x8a, 0x69, 0xd9, 0x61, 0xc4, 0x1c, 0x46,
	0xd2, 0xed, 0xb4, 0x97, 0x47, 0xc2, 0x3e, 0xab, 0x77, 0x2c, 0x72, 0x98, 0x34, 0xd4, 0x1c, 0xc8,
	0xae, 0xf5, 0x55, 0x79, 0x1c, 0xb0, 0xdc, 0xa5, 0xc2, 0x4d, 0x77, 0xd4, 0x86, 0x70, 0xc8, 0x5a,
	0x04, 0x61, 0xae, 0xae, 0x3c, 0xad, 0x2d, 0x55, 0x9e, 0x6a, 0x1c, 0xb1, 0xc9, 0x2e, 0x25, 0xde,
	0xc2, 0xc0, 0x57, 0xf6, 0x44, 0x1e, 0xc7, 0x3c, 0xd8, 0x22, 0xf1, 0x19, 0x86, 0x71, 0xbd, 0x43,
	0xe0, 0xc0, 0x16, 0x8f, 0x81, 0x45, 0xfc, 0x83, 0x9b, 0x38, 0xe3, 0xf2, 0x36, 0x11, 0x42, 0xf1,
	0x7f, 0x0d, 0xe1, 0x84, 0x57, 0x72, 0x1d, 0xac, 0x70, 0x66, 0x5f, 0x75, 0x53, 0x49, 0x85, 0xaf,
	0xa2, 0x95, 0x0e, 0x15, 0x03, 0xf8, 0xa6, 0xed, 0x41, 0xd6, 0x38, 0xbd, 0x05, 0x10, 0xf1, 0xfc,
	0x5f, 0x02, 0xb3, 0xc7, 0x7b, 0xc1, 0x7b, 0xbc, 0xd8, 0x3e, 0xa5, 0x45, 0x61, 0x91, 0x92, 0xc7,
	0xf3, 0xee, 0xf9, 0x2f, 0x77, 0x2c, 0x16, 0x00, 0xce, 0x50, 0x75, 0xde, 0xfb, 0xca, 0x13, 0x3f,
	0x68, 0xfa, 0x29, 0xf9, 0x50, 0x76, 0xc8, 0xe0, 0xde, 0xea, 0x0b, 0xb5, 0x2f, 0xe2, 0x5a, 0xcc,
	0x20, 0x75, 0xf4, 0xa7, 0xfd, 0x4b, 0x28, 0xbf, 0xf4, 0xbe, 0xa7, 0x4f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc7, 0x76, 0x75, 0x89, 0x8a, 0x02, 0x00, 0x00,
}
