// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetOwnerGroups.proto

package GetOwnerGroups

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOwnerGroupsInner struct {
	Asker                *uint64  `protobuf:"varint,1,req,name=asker" json:"asker,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	PageSize             *int32   `protobuf:"varint,3,opt,name=pageSize" json:"pageSize,omitempty"`
	Target               *uint32  `protobuf:"varint,4,opt,name=target" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOwnerGroupsInner) Reset()         { *m = GetOwnerGroupsInner{} }
func (m *GetOwnerGroupsInner) String() string { return proto.CompactTextString(m) }
func (*GetOwnerGroupsInner) ProtoMessage()    {}
func (*GetOwnerGroupsInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6b258ff9b734d30, []int{0}
}

func (m *GetOwnerGroupsInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOwnerGroupsInner.Unmarshal(m, b)
}
func (m *GetOwnerGroupsInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOwnerGroupsInner.Marshal(b, m, deterministic)
}
func (m *GetOwnerGroupsInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOwnerGroupsInner.Merge(m, src)
}
func (m *GetOwnerGroupsInner) XXX_Size() int {
	return xxx_messageInfo_GetOwnerGroupsInner.Size(m)
}
func (m *GetOwnerGroupsInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOwnerGroupsInner.DiscardUnknown(m)
}

var xxx_messageInfo_GetOwnerGroupsInner proto.InternalMessageInfo

func (m *GetOwnerGroupsInner) GetAsker() uint64 {
	if m != nil && m.Asker != nil {
		return *m.Asker
	}
	return 0
}

func (m *GetOwnerGroupsInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GetOwnerGroupsInner) GetPageSize() int32 {
	if m != nil && m.PageSize != nil {
		return *m.PageSize
	}
	return 0
}

func (m *GetOwnerGroupsInner) GetTarget() uint32 {
	if m != nil && m.Target != nil {
		return *m.Target
	}
	return 0
}

func init() {
	proto.RegisterType((*GetOwnerGroupsInner)(nil), "GetOwnerGroupsInner")
}

func init() { proto.RegisterFile("GetOwnerGroups.proto", fileDescriptor_e6b258ff9b734d30) }

var fileDescriptor_e6b258ff9b734d30 = []byte{
	// 133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0x4f, 0x2d, 0xf1,
	0x2f, 0xcf, 0x4b, 0x2d, 0x72, 0x2f, 0xca, 0x2f, 0x2d, 0x28, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0xaa, 0xe4, 0x12, 0x46, 0x15, 0xf7, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x12, 0xe1, 0x62, 0x4d,
	0x2c, 0xce, 0x4e, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd2, 0x60, 0x09, 0x82, 0x70, 0x84, 0x24, 0xb8,
	0xd8, 0xd3, 0x41, 0x8a, 0x3c, 0x53, 0x24, 0x98, 0xc0, 0xe2, 0x30, 0xae, 0x90, 0x14, 0x17, 0x47,
	0x41, 0x62, 0x7a, 0x6a, 0x70, 0x66, 0x55, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x9c,
	0x2f, 0x24, 0xc6, 0xc5, 0x56, 0x92, 0x58, 0x94, 0x9e, 0x5a, 0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1,
	0x1b, 0x04, 0xe5, 0x39, 0x31, 0x79, 0x30, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f, 0x0b, 0xa1,
	0x16, 0x95, 0x00, 0x00, 0x00,
}
