// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GetPublicGroupsResp.proto

package GetPublicGroupsResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPublicGroupsRespInner struct {
	Groups               []*PublicGroupSimpleInfo `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetPublicGroupsRespInner) Reset()         { *m = GetPublicGroupsRespInner{} }
func (m *GetPublicGroupsRespInner) String() string { return proto.CompactTextString(m) }
func (*GetPublicGroupsRespInner) ProtoMessage()    {}
func (*GetPublicGroupsRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1dd143bd4a028d, []int{0}
}

func (m *GetPublicGroupsRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPublicGroupsRespInner.Unmarshal(m, b)
}
func (m *GetPublicGroupsRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPublicGroupsRespInner.Marshal(b, m, deterministic)
}
func (m *GetPublicGroupsRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPublicGroupsRespInner.Merge(m, src)
}
func (m *GetPublicGroupsRespInner) XXX_Size() int {
	return xxx_messageInfo_GetPublicGroupsRespInner.Size(m)
}
func (m *GetPublicGroupsRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPublicGroupsRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_GetPublicGroupsRespInner proto.InternalMessageInfo

func (m *GetPublicGroupsRespInner) GetGroups() []*PublicGroupSimpleInfo {
	if m != nil {
		return m.Groups
	}
	return nil
}

type PublicGroupSimpleInfo struct {
	GroupId              *uint64  `protobuf:"varint,1,req,name=groupId" json:"groupId,omitempty"`
	Name                 *string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Owner                *uint64  `protobuf:"varint,3,opt,name=owner" json:"owner,omitempty"`
	Permission           *uint32  `protobuf:"varint,4,opt,name=permission" json:"permission,omitempty"`
	MemberCount          *uint32  `protobuf:"varint,5,opt,name=memberCount" json:"memberCount,omitempty"`
	Scope                *uint32  `protobuf:"varint,6,opt,name=scope" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicGroupSimpleInfo) Reset()         { *m = PublicGroupSimpleInfo{} }
func (m *PublicGroupSimpleInfo) String() string { return proto.CompactTextString(m) }
func (*PublicGroupSimpleInfo) ProtoMessage()    {}
func (*PublicGroupSimpleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e1dd143bd4a028d, []int{1}
}

func (m *PublicGroupSimpleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicGroupSimpleInfo.Unmarshal(m, b)
}
func (m *PublicGroupSimpleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicGroupSimpleInfo.Marshal(b, m, deterministic)
}
func (m *PublicGroupSimpleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicGroupSimpleInfo.Merge(m, src)
}
func (m *PublicGroupSimpleInfo) XXX_Size() int {
	return xxx_messageInfo_PublicGroupSimpleInfo.Size(m)
}
func (m *PublicGroupSimpleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicGroupSimpleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PublicGroupSimpleInfo proto.InternalMessageInfo

func (m *PublicGroupSimpleInfo) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *PublicGroupSimpleInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PublicGroupSimpleInfo) GetOwner() uint64 {
	if m != nil && m.Owner != nil {
		return *m.Owner
	}
	return 0
}

func (m *PublicGroupSimpleInfo) GetPermission() uint32 {
	if m != nil && m.Permission != nil {
		return *m.Permission
	}
	return 0
}

func (m *PublicGroupSimpleInfo) GetMemberCount() uint32 {
	if m != nil && m.MemberCount != nil {
		return *m.MemberCount
	}
	return 0
}

func (m *PublicGroupSimpleInfo) GetScope() uint32 {
	if m != nil && m.Scope != nil {
		return *m.Scope
	}
	return 0
}

func init() {
	proto.RegisterType((*GetPublicGroupsRespInner)(nil), "GetPublicGroupsRespInner")
	proto.RegisterType((*PublicGroupSimpleInfo)(nil), "PublicGroupSimpleInfo")
}

func init() { proto.RegisterFile("GetPublicGroupsResp.proto", fileDescriptor_2e1dd143bd4a028d) }

var fileDescriptor_2e1dd143bd4a028d = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xc9, 0xb6, 0xbb, 0xe2, 0x2c, 0x5e, 0x82, 0x4a, 0xbc, 0x48, 0xe8, 0x41, 0x7a, 0xca,
	0xc1, 0x47, 0xd0, 0xc3, 0x5a, 0x4f, 0x12, 0x9f, 0xc0, 0xd6, 0xd9, 0x12, 0x68, 0x66, 0x42, 0xd2,
	0xa0, 0x3e, 0x97, 0x2f, 0x28, 0xa6, 0x0a, 0x3d, 0xec, 0x2d, 0xdf, 0xf7, 0x7f, 0xe4, 0x30, 0x70,
	0x73, 0xc0, 0xf9, 0x25, 0xf7, 0x93, 0x1b, 0x0e, 0x91, 0x73, 0x48, 0x16, 0x53, 0x30, 0x21, 0xf2,
	0xcc, 0xcd, 0x33, 0xa8, 0x13, 0x63, 0x47, 0x84, 0x51, 0x1a, 0xd8, 0x8d, 0x45, 0x29, 0xa1, 0xab,
	0x76, 0x7f, 0x7f, 0x6d, 0x56, 0xdd, 0xab, 0xf3, 0x61, 0xc2, 0x8e, 0x8e, 0x6c, 0xff, 0xaa, 0xe6,
	0x5b, 0xc0, 0xd5, 0xc9, 0x42, 0x2a, 0x38, 0x2b, 0x4d, 0xf7, 0xae, 0x84, 0xde, 0xb4, 0xb5, 0xfd,
	0x47, 0x29, 0xa1, 0xa6, 0x37, 0x8f, 0x6a, 0xa3, 0x45, 0x7b, 0x6e, 0xcb, 0x5b, 0x5e, 0xc2, 0x96,
	0x3f, 0x08, 0xa3, 0xaa, 0xb4, 0x68, 0x6b, 0xbb, 0x80, 0xbc, 0x05, 0x08, 0x18, 0xbd, 0x4b, 0xc9,
	0x31, 0xa9, 0x5a, 0x8b, 0xf6, 0xc2, 0xae, 0x8c, 0xd4, 0xb0, 0xf7, 0xe8, 0x7b, 0x8c, 0x8f, 0x9c,
	0x69, 0x56, 0xdb, 0x12, 0xac, 0xd5, 0xef, 0xbf, 0x69, 0xe0, 0x80, 0x6a, 0x57, 0xb6, 0x05, 0x1e,
	0xee, 0xa0, 0x19, 0xd8, 0x9b, 0xaf, 0x4c, 0x33, 0xd3, 0xf8, 0x99, 0xc9, 0x4c, 0x3c, 0xba, 0xc1,
	0x0c, 0x1c, 0x71, 0x39, 0x52, 0x9f, 0x8f, 0x4f, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0x81, 0xd9, 0xe1, 0x45, 0x01, 0x00, 0x00,
}
