// Code generated by protoc-gen-go. DO NOT EDIT.
// source: GroupNotify.proto

package GroupNotify

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupNotifyMessageInner struct {
	MsgType              *uint32  `protobuf:"varint,1,opt,name=msgType" json:"msgType,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,opt,name=groupId" json:"groupId,omitempty"`
	DateCreated          *string  `protobuf:"bytes,3,opt,name=dateCreated" json:"dateCreated,omitempty"`
	Admin                *string  `protobuf:"bytes,4,opt,name=admin" json:"admin,omitempty"`
	Declared             *string  `protobuf:"bytes,5,opt,name=declared" json:"declared,omitempty"`
	Confirm              *uint32  `protobuf:"varint,6,opt,name=confirm" json:"confirm,omitempty"`
	Member               *string  `protobuf:"bytes,7,opt,name=member" json:"member,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupNotifyMessageInner) Reset()         { *m = GroupNotifyMessageInner{} }
func (m *GroupNotifyMessageInner) String() string { return proto.CompactTextString(m) }
func (*GroupNotifyMessageInner) ProtoMessage()    {}
func (*GroupNotifyMessageInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_4139a1215c88762f, []int{0}
}

func (m *GroupNotifyMessageInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupNotifyMessageInner.Unmarshal(m, b)
}
func (m *GroupNotifyMessageInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupNotifyMessageInner.Marshal(b, m, deterministic)
}
func (m *GroupNotifyMessageInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupNotifyMessageInner.Merge(m, src)
}
func (m *GroupNotifyMessageInner) XXX_Size() int {
	return xxx_messageInfo_GroupNotifyMessageInner.Size(m)
}
func (m *GroupNotifyMessageInner) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupNotifyMessageInner.DiscardUnknown(m)
}

var xxx_messageInfo_GroupNotifyMessageInner proto.InternalMessageInfo

func (m *GroupNotifyMessageInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *GroupNotifyMessageInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupNotifyMessageInner) GetDateCreated() string {
	if m != nil && m.DateCreated != nil {
		return *m.DateCreated
	}
	return ""
}

func (m *GroupNotifyMessageInner) GetAdmin() string {
	if m != nil && m.Admin != nil {
		return *m.Admin
	}
	return ""
}

func (m *GroupNotifyMessageInner) GetDeclared() string {
	if m != nil && m.Declared != nil {
		return *m.Declared
	}
	return ""
}

func (m *GroupNotifyMessageInner) GetConfirm() uint32 {
	if m != nil && m.Confirm != nil {
		return *m.Confirm
	}
	return 0
}

func (m *GroupNotifyMessageInner) GetMember() string {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return ""
}

func init() {
	proto.RegisterType((*GroupNotifyMessageInner)(nil), "GroupNotifyMessageInner")
}

func init() { proto.RegisterFile("GroupNotify.proto", fileDescriptor_4139a1215c88762f) }

var fileDescriptor_4139a1215c88762f = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x70, 0xe2, 0xfe, 0xd3, 0x11, 0x0f, 0x06, 0xd1, 0xc1, 0x53, 0xd9, 0x83, 0xf4, 0xd4,
	0x87, 0xd0, 0x83, 0xee, 0x41, 0x0f, 0xc5, 0x17, 0xc8, 0x26, 0xd3, 0x50, 0xd8, 0x64, 0xca, 0x34,
	0x01, 0xfb, 0x9c, 0xbe, 0x90, 0xb4, 0xdd, 0x95, 0x1e, 0x7f, 0xdf, 0xc7, 0x47, 0x32, 0x70, 0xff,
	0x2e, 0x9c, 0xbb, 0x2f, 0x4e, 0x6d, 0x33, 0x54, 0x9d, 0x70, 0xe2, 0xfd, 0xaf, 0x82, 0xa7, 0x45,
	0xfa, 0x49, 0x7d, 0x6f, 0x3c, 0x1d, 0x62, 0x24, 0xd1, 0x08, 0xbb, 0xd0, 0xfb, 0xef, 0xa1, 0x23,
	0x54, 0x85, 0x2a, 0xef, 0xea, 0x0b, 0xc7, 0xc6, 0x8f, 0xa3, 0x83, 0xc3, 0xab, 0x42, 0x95, 0xeb,
	0xfa, 0x42, 0x5d, 0xc0, 0xad, 0x33, 0x89, 0xde, 0x84, 0x4c, 0x22, 0x87, 0xab, 0x42, 0x95, 0x37,
	0xf5, 0x32, 0xd2, 0x0f, 0xb0, 0x31, 0x2e, 0xb4, 0x11, 0xd7, 0x53, 0x37, 0x43, 0x3f, 0xc3, 0xb5,
	0x23, 0x7b, 0x32, 0x42, 0x0e, 0x37, 0x53, 0xf1, 0xef, 0xf1, 0x35, 0xcb, 0xb1, 0x69, 0x25, 0xe0,
	0x76, 0xfe, 0xc7, 0x99, 0xfa, 0x11, 0xb6, 0x81, 0xc2, 0x91, 0x04, 0x77, 0xd3, 0xe6, 0xac, 0xd7,
	0x17, 0xd8, 0x5b, 0x0e, 0xd5, 0x90, 0x63, 0xe2, 0xe8, 0x7f, 0x72, 0xac, 0x4e, 0xec, 0x5b, 0x5b,
	0x59, 0x16, 0x9a, 0x0f, 0x3f, 0xe6, 0xe6, 0x63, 0xf5, 0x17, 0x00, 0x00, 0xff, 0xff, 0x57, 0x93,
	0x4f, 0x9d, 0x11, 0x01, 0x00, 0x00,
}
