// Code generated by protoc-gen-go. DO NOT EDIT.
// source: InviteJoinGroupResp.proto

package InviteJoinGroupResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InviteJoinGroupRespInner struct {
	FailInfos            []*FailInfo `protobuf:"bytes,1,rep,name=failInfos" json:"failInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InviteJoinGroupRespInner) Reset()         { *m = InviteJoinGroupRespInner{} }
func (m *InviteJoinGroupRespInner) String() string { return proto.CompactTextString(m) }
func (*InviteJoinGroupRespInner) ProtoMessage()    {}
func (*InviteJoinGroupRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7aa82dbf6cf3ee, []int{0}
}

func (m *InviteJoinGroupRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteJoinGroupRespInner.Unmarshal(m, b)
}
func (m *InviteJoinGroupRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteJoinGroupRespInner.Marshal(b, m, deterministic)
}
func (m *InviteJoinGroupRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteJoinGroupRespInner.Merge(m, src)
}
func (m *InviteJoinGroupRespInner) XXX_Size() int {
	return xxx_messageInfo_InviteJoinGroupRespInner.Size(m)
}
func (m *InviteJoinGroupRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteJoinGroupRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_InviteJoinGroupRespInner proto.InternalMessageInfo

func (m *InviteJoinGroupRespInner) GetFailInfos() []*FailInfo {
	if m != nil {
		return m.FailInfos
	}
	return nil
}

type FailInfo struct {
	Member               *uint64  `protobuf:"varint,1,opt,name=member" json:"member,omitempty"`
	Reason               *uint32  `protobuf:"varint,2,opt,name=reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailInfo) Reset()         { *m = FailInfo{} }
func (m *FailInfo) String() string { return proto.CompactTextString(m) }
func (*FailInfo) ProtoMessage()    {}
func (*FailInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc7aa82dbf6cf3ee, []int{1}
}

func (m *FailInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailInfo.Unmarshal(m, b)
}
func (m *FailInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailInfo.Marshal(b, m, deterministic)
}
func (m *FailInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailInfo.Merge(m, src)
}
func (m *FailInfo) XXX_Size() int {
	return xxx_messageInfo_FailInfo.Size(m)
}
func (m *FailInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FailInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FailInfo proto.InternalMessageInfo

func (m *FailInfo) GetMember() uint64 {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return 0
}

func (m *FailInfo) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func init() {
	proto.RegisterType((*InviteJoinGroupRespInner)(nil), "InviteJoinGroupRespInner")
	proto.RegisterType((*FailInfo)(nil), "FailInfo")
}

func init() { proto.RegisterFile("InviteJoinGroupResp.proto", fileDescriptor_cc7aa82dbf6cf3ee) }

var fileDescriptor_cc7aa82dbf6cf3ee = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xf4, 0xcc, 0x2b, 0xcb,
	0x2c, 0x49, 0xf5, 0xca, 0xcf, 0xcc, 0x73, 0x2f, 0xca, 0x2f, 0x2d, 0x08, 0x4a, 0x2d, 0x2e, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe6, 0x92, 0xc0, 0x22, 0xe9, 0x99, 0x97, 0x97, 0x5a,
	0x24, 0xa4, 0xce, 0xc5, 0x99, 0x96, 0x98, 0x99, 0xe3, 0x99, 0x97, 0x96, 0x5f, 0x2c, 0xc1, 0xa8,
	0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa9, 0xe7, 0x06, 0x15, 0x09, 0x42, 0xc8, 0x29, 0x59, 0x71, 0x71,
	0xc0, 0x84, 0x85, 0xc4, 0xb8, 0xd8, 0x72, 0x53, 0x73, 0x93, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x82, 0xa0, 0x3c, 0x90, 0x78, 0x51, 0x6a, 0x62, 0x71, 0x7e, 0x9e, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x6f, 0x10, 0x94, 0xe7, 0xa4, 0xc6, 0xa5, 0x94, 0x9c, 0x9f, 0xab, 0x57, 0x59, 0x9a,
	0x57, 0x92, 0x9f, 0x97, 0x5e, 0x51, 0x9a, 0xa7, 0x97, 0x93, 0x9f, 0x9e, 0x99, 0xac, 0x97, 0x9c,
	0x5f, 0x94, 0x0a, 0x71, 0x63, 0x52, 0x69, 0x9a, 0x07, 0x33, 0x20, 0x00, 0x00, 0xff, 0xff, 0x31,
	0x6e, 0x47, 0xcc, 0xc4, 0x00, 0x00, 0x00,
}
