// Code generated by protoc-gen-go. DO NOT EDIT.
// source: InviteJoinGroup.proto

package InviteJoinGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InviteJoinGroupInner struct {
	Invitor              *uint64  `protobuf:"varint,1,opt,name=invitor" json:"invitor,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	Declared             *string  `protobuf:"bytes,3,opt,name=declared" json:"declared,omitempty"`
	Members              []uint64 `protobuf:"varint,4,rep,name=members" json:"members,omitempty"`
	Confirm              *uint32  `protobuf:"varint,5,opt,name=confirm" json:"confirm,omitempty"`
	Ext                  *string  `protobuf:"bytes,6,opt,name=ext" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InviteJoinGroupInner) Reset()         { *m = InviteJoinGroupInner{} }
func (m *InviteJoinGroupInner) String() string { return proto.CompactTextString(m) }
func (*InviteJoinGroupInner) ProtoMessage()    {}
func (*InviteJoinGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b1c8ccfb92b9fb8, []int{0}
}

func (m *InviteJoinGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InviteJoinGroupInner.Unmarshal(m, b)
}
func (m *InviteJoinGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InviteJoinGroupInner.Marshal(b, m, deterministic)
}
func (m *InviteJoinGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InviteJoinGroupInner.Merge(m, src)
}
func (m *InviteJoinGroupInner) XXX_Size() int {
	return xxx_messageInfo_InviteJoinGroupInner.Size(m)
}
func (m *InviteJoinGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_InviteJoinGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_InviteJoinGroupInner proto.InternalMessageInfo

func (m *InviteJoinGroupInner) GetInvitor() uint64 {
	if m != nil && m.Invitor != nil {
		return *m.Invitor
	}
	return 0
}

func (m *InviteJoinGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *InviteJoinGroupInner) GetDeclared() string {
	if m != nil && m.Declared != nil {
		return *m.Declared
	}
	return ""
}

func (m *InviteJoinGroupInner) GetMembers() []uint64 {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *InviteJoinGroupInner) GetConfirm() uint32 {
	if m != nil && m.Confirm != nil {
		return *m.Confirm
	}
	return 0
}

func (m *InviteJoinGroupInner) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

func init() {
	proto.RegisterType((*InviteJoinGroupInner)(nil), "InviteJoinGroupInner")
}

func init() { proto.RegisterFile("InviteJoinGroup.proto", fileDescriptor_9b1c8ccfb92b9fb8) }

var fileDescriptor_9b1c8ccfb92b9fb8 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xcd, 0x6a, 0x85, 0x30,
	0x10, 0x85, 0x89, 0xb1, 0x7f, 0x81, 0x42, 0x91, 0x16, 0x42, 0x57, 0xc1, 0x45, 0x71, 0x95, 0x87,
	0xe8, 0xa6, 0xb5, 0x4b, 0xdf, 0xa0, 0xc6, 0x51, 0x02, 0x66, 0x46, 0xa6, 0x49, 0xb1, 0xef, 0xd4,
	0x87, 0xbc, 0xc4, 0xab, 0x77, 0x71, 0x77, 0xf3, 0xcd, 0x37, 0x67, 0xe0, 0xa8, 0x97, 0x16, 0x7f,
	0x7d, 0x84, 0x2f, 0xf2, 0xf8, 0xc1, 0x94, 0x16, 0xbb, 0x30, 0x45, 0xaa, 0xff, 0x85, 0x7a, 0xbe,
	0x32, 0x2d, 0x22, 0x70, 0xa5, 0xd5, 0x9d, 0xcf, 0x7b, 0x62, 0x2d, 0x8c, 0x68, 0xca, 0xee, 0xc0,
	0x6c, 0xa6, 0xed, 0x6e, 0xd0, 0x85, 0x29, 0xb2, 0xd9, 0xb1, 0x7a, 0x55, 0xf7, 0x03, 0xb8, 0xf9,
	0x9b, 0x61, 0xd0, 0xd2, 0x88, 0xe6, 0xa1, 0xbb, 0x70, 0x4e, 0x05, 0x08, 0x3d, 0xf0, 0x8f, 0x2e,
	0x8d, 0xcc, 0xa9, 0x1d, 0xb3, 0x71, 0x84, 0xa3, 0xe7, 0xa0, 0x6f, 0x8c, 0x68, 0x1e, 0xbb, 0x03,
	0xab, 0x27, 0x25, 0x61, 0x8d, 0xfa, 0x76, 0x7b, 0x95, 0xc7, 0xf7, 0x37, 0x55, 0x3b, 0x0a, 0xf6,
	0x2f, 0x61, 0x24, 0x9c, 0xd6, 0x84, 0x76, 0xa6, 0xc9, 0x3b, 0xeb, 0x88, 0xe1, 0xdc, 0xa8, 0x4f,
	0xe3, 0xa7, 0x3c, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xa7, 0x9d, 0xcb, 0xee, 0x00, 0x00, 0x00,
}
