// Code generated by protoc-gen-go. DO NOT EDIT.
// source: JoinGroup.proto

package JoinGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JoinGroupInner struct {
	Joiner               *uint64  `protobuf:"varint,1,req,name=joiner" json:"joiner,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	Declared             *string  `protobuf:"bytes,3,opt,name=declared" json:"declared,omitempty"`
	Ext                  *string  `protobuf:"bytes,4,opt,name=ext" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupInner) Reset()         { *m = JoinGroupInner{} }
func (m *JoinGroupInner) String() string { return proto.CompactTextString(m) }
func (*JoinGroupInner) ProtoMessage()    {}
func (*JoinGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_6d90f2b91f1023c7, []int{0}
}

func (m *JoinGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupInner.Unmarshal(m, b)
}
func (m *JoinGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupInner.Marshal(b, m, deterministic)
}
func (m *JoinGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupInner.Merge(m, src)
}
func (m *JoinGroupInner) XXX_Size() int {
	return xxx_messageInfo_JoinGroupInner.Size(m)
}
func (m *JoinGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupInner proto.InternalMessageInfo

func (m *JoinGroupInner) GetJoiner() uint64 {
	if m != nil && m.Joiner != nil {
		return *m.Joiner
	}
	return 0
}

func (m *JoinGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *JoinGroupInner) GetDeclared() string {
	if m != nil && m.Declared != nil {
		return *m.Declared
	}
	return ""
}

func (m *JoinGroupInner) GetExt() string {
	if m != nil && m.Ext != nil {
		return *m.Ext
	}
	return ""
}

func init() {
	proto.RegisterType((*JoinGroupInner)(nil), "JoinGroupInner")
}

func init() { proto.RegisterFile("JoinGroup.proto", fileDescriptor_6d90f2b91f1023c7) }

var fileDescriptor_6d90f2b91f1023c7 = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf7, 0xca, 0xcf, 0xcc,
	0x73, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x2a, 0xe0, 0xe2, 0x83,
	0x0b, 0x79, 0xe6, 0xe5, 0xa5, 0x16, 0x09, 0x89, 0x71, 0xb1, 0x65, 0xe5, 0x67, 0xe6, 0xa5, 0x16,
	0x49, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x04, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0xe9, 0x60, 0x55,
	0x29, 0x12, 0x4c, 0x60, 0x09, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0x23, 0x25, 0x35, 0x39, 0x27, 0xb1,
	0x28, 0x35, 0x45, 0x82, 0x59, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x12, 0xe0, 0x62, 0x4e,
	0xad, 0x28, 0x91, 0x60, 0x01, 0x0b, 0x83, 0x98, 0x4e, 0x4c, 0x1e, 0xcc, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9a, 0x71, 0xfe, 0x33, 0x87, 0x00, 0x00, 0x00,
}
