// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ModifyMemberCard.proto

package ModifyMemberCard

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ModifyMemberCardInner struct {
	Belong               *uint64  `protobuf:"varint,1,req,name=belong" json:"belong,omitempty"`
	Member               *uint64  `protobuf:"varint,2,opt,name=member" json:"member,omitempty"`
	Display              *string  `protobuf:"bytes,3,opt,name=display" json:"display,omitempty"`
	Phone                *string  `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Mail                 *string  `protobuf:"bytes,5,opt,name=mail" json:"mail,omitempty"`
	Remark               *string  `protobuf:"bytes,6,opt,name=remark" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifyMemberCardInner) Reset()         { *m = ModifyMemberCardInner{} }
func (m *ModifyMemberCardInner) String() string { return proto.CompactTextString(m) }
func (*ModifyMemberCardInner) ProtoMessage()    {}
func (*ModifyMemberCardInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_29387d6ceb69a768, []int{0}
}

func (m *ModifyMemberCardInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyMemberCardInner.Unmarshal(m, b)
}
func (m *ModifyMemberCardInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyMemberCardInner.Marshal(b, m, deterministic)
}
func (m *ModifyMemberCardInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyMemberCardInner.Merge(m, src)
}
func (m *ModifyMemberCardInner) XXX_Size() int {
	return xxx_messageInfo_ModifyMemberCardInner.Size(m)
}
func (m *ModifyMemberCardInner) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyMemberCardInner.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyMemberCardInner proto.InternalMessageInfo

func (m *ModifyMemberCardInner) GetBelong() uint64 {
	if m != nil && m.Belong != nil {
		return *m.Belong
	}
	return 0
}

func (m *ModifyMemberCardInner) GetMember() uint64 {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return 0
}

func (m *ModifyMemberCardInner) GetDisplay() string {
	if m != nil && m.Display != nil {
		return *m.Display
	}
	return ""
}

func (m *ModifyMemberCardInner) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *ModifyMemberCardInner) GetMail() string {
	if m != nil && m.Mail != nil {
		return *m.Mail
	}
	return ""
}

func (m *ModifyMemberCardInner) GetRemark() string {
	if m != nil && m.Remark != nil {
		return *m.Remark
	}
	return ""
}

func init() {
	proto.RegisterType((*ModifyMemberCardInner)(nil), "ModifyMemberCardInner")
}

func init() { proto.RegisterFile("ModifyMemberCard.proto", fileDescriptor_29387d6ceb69a768) }

var fileDescriptor_29387d6ceb69a768 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xf3, 0xcd, 0x4f, 0xc9,
	0x4c, 0xab, 0xf4, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0x72, 0x4e, 0x2c, 0x4a, 0xd1, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0x5a, 0xcc, 0xc8, 0x25, 0x8a, 0x2e, 0xe5, 0x99, 0x97, 0x97, 0x5a, 0x24, 0x24,
	0xc6, 0xc5, 0x96, 0x94, 0x9a, 0x93, 0x9f, 0x97, 0x2e, 0xc1, 0xa8, 0xc0, 0xa4, 0xc1, 0x12, 0x04,
	0xe5, 0x81, 0xc4, 0x73, 0xc1, 0x4a, 0x25, 0x98, 0x14, 0x18, 0x41, 0xe2, 0x10, 0x9e, 0x90, 0x04,
	0x17, 0x7b, 0x4a, 0x66, 0x71, 0x41, 0x4e, 0x62, 0xa5, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10,
	0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x5a, 0x90, 0x91, 0x9f, 0x97, 0x2a, 0xc1, 0x02, 0x16, 0x87, 0x70,
	0x84, 0x84, 0xb8, 0x58, 0x72, 0x13, 0x33, 0x73, 0x24, 0x58, 0xc1, 0x82, 0x60, 0x36, 0xc8, 0xec,
	0xa2, 0xd4, 0xdc, 0xc4, 0xa2, 0x6c, 0x09, 0x36, 0xb0, 0x28, 0x94, 0xe7, 0xc4, 0xe4, 0xc1, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0xec, 0x1a, 0xa4, 0x25, 0xc2, 0x00, 0x00, 0x00,
}
