// Code generated by protoc-gen-go. DO NOT EDIT.
// source: QueryGroupMemberCardResp.proto

package QueryGroupMemberCardResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryGroupMemberCardRespInner struct {
	Member               *uint64  `protobuf:"varint,1,opt,name=member" json:"member,omitempty"`
	Groupid              *uint64  `protobuf:"varint,2,req,name=groupid" json:"groupid,omitempty"`
	Display              *string  `protobuf:"bytes,3,opt,name=display" json:"display,omitempty"`
	Phone                *string  `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	Mail                 *string  `protobuf:"bytes,5,opt,name=mail" json:"mail,omitempty"`
	Remark               *string  `protobuf:"bytes,6,opt,name=remark" json:"remark,omitempty"`
	SpeakState           *uint32  `protobuf:"varint,7,opt,name=speakState,def=1" json:"speakState,omitempty"`
	Role                 *uint32  `protobuf:"varint,8,opt,name=role" json:"role,omitempty"`
	Sex                  *uint32  `protobuf:"varint,9,opt,name=sex" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryGroupMemberCardRespInner) Reset()         { *m = QueryGroupMemberCardRespInner{} }
func (m *QueryGroupMemberCardRespInner) String() string { return proto.CompactTextString(m) }
func (*QueryGroupMemberCardRespInner) ProtoMessage()    {}
func (*QueryGroupMemberCardRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_196df88f56a09632, []int{0}
}

func (m *QueryGroupMemberCardRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryGroupMemberCardRespInner.Unmarshal(m, b)
}
func (m *QueryGroupMemberCardRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryGroupMemberCardRespInner.Marshal(b, m, deterministic)
}
func (m *QueryGroupMemberCardRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGroupMemberCardRespInner.Merge(m, src)
}
func (m *QueryGroupMemberCardRespInner) XXX_Size() int {
	return xxx_messageInfo_QueryGroupMemberCardRespInner.Size(m)
}
func (m *QueryGroupMemberCardRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGroupMemberCardRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGroupMemberCardRespInner proto.InternalMessageInfo

const Default_QueryGroupMemberCardRespInner_SpeakState uint32 = 1

func (m *QueryGroupMemberCardRespInner) GetMember() uint64 {
	if m != nil && m.Member != nil {
		return *m.Member
	}
	return 0
}

func (m *QueryGroupMemberCardRespInner) GetGroupid() uint64 {
	if m != nil && m.Groupid != nil {
		return *m.Groupid
	}
	return 0
}

func (m *QueryGroupMemberCardRespInner) GetDisplay() string {
	if m != nil && m.Display != nil {
		return *m.Display
	}
	return ""
}

func (m *QueryGroupMemberCardRespInner) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *QueryGroupMemberCardRespInner) GetMail() string {
	if m != nil && m.Mail != nil {
		return *m.Mail
	}
	return ""
}

func (m *QueryGroupMemberCardRespInner) GetRemark() string {
	if m != nil && m.Remark != nil {
		return *m.Remark
	}
	return ""
}

func (m *QueryGroupMemberCardRespInner) GetSpeakState() uint32 {
	if m != nil && m.SpeakState != nil {
		return *m.SpeakState
	}
	return Default_QueryGroupMemberCardRespInner_SpeakState
}

func (m *QueryGroupMemberCardRespInner) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *QueryGroupMemberCardRespInner) GetSex() uint32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryGroupMemberCardRespInner)(nil), "QueryGroupMemberCardRespInner")
}

func init() { proto.RegisterFile("QueryGroupMemberCardResp.proto", fileDescriptor_196df88f56a09632) }

var fileDescriptor_196df88f56a09632 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8d, 0x3d, 0x4b, 0xc5, 0x30,
	0x14, 0x86, 0x49, 0x9b, 0x7b, 0xaf, 0x3d, 0x20, 0x48, 0x10, 0x39, 0x8b, 0x12, 0x9d, 0x32, 0x09,
	0xae, 0x8e, 0x3a, 0xa8, 0x83, 0x83, 0xf1, 0x17, 0x44, 0x7a, 0xd0, 0xd2, 0xa6, 0x09, 0x27, 0x2d,
	0xd8, 0x3f, 0xee, 0x2c, 0x89, 0x2d, 0xb8, 0xdc, 0xed, 0x7d, 0x9e, 0xf7, 0x7c, 0xc0, 0xd5, 0xdb,
	0x4c, 0xbc, 0x3c, 0x71, 0x98, 0xe3, 0x2b, 0xf9, 0x0f, 0xe2, 0x47, 0xc7, 0xad, 0xa5, 0x14, 0x6f,
	0x23, 0x87, 0x29, 0xdc, 0xfc, 0x08, 0xb8, 0x3c, 0x36, 0xf2, 0x32, 0x8e, 0xc4, 0xea, 0x02, 0xf6,
	0xbe, 0x68, 0x14, 0x5a, 0x18, 0x69, 0x57, 0x52, 0x08, 0x87, 0xcf, 0xbc, 0xd3, 0xb5, 0x58, 0xe9,
	0xca, 0x48, 0xbb, 0x61, 0x6e, 0xda, 0x2e, 0xc5, 0xc1, 0x2d, 0x58, 0x6b, 0x61, 0x1a, 0xbb, 0xa1,
	0x3a, 0x87, 0x5d, 0xfc, 0x0a, 0x23, 0xa1, 0x2c, 0xfe, 0x0f, 0x94, 0x02, 0xe9, 0x5d, 0x37, 0xe0,
	0xae, 0xc8, 0x92, 0xf3, 0x57, 0x26, 0xef, 0xb8, 0xc7, 0x7d, 0xb1, 0x2b, 0xa9, 0x6b, 0x80, 0x14,
	0xc9, 0xf5, 0xef, 0x93, 0x9b, 0x08, 0x0f, 0x5a, 0x98, 0xd3, 0x7b, 0x71, 0x67, 0xff, 0xc9, 0x7c,
	0x8e, 0xc3, 0x40, 0x78, 0x92, 0x4b, 0x5b, 0xb2, 0x3a, 0x83, 0x3a, 0xd1, 0x37, 0x36, 0x45, 0xe5,
	0xf8, 0x50, 0x3d, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xf6, 0xa7, 0xee, 0x1d, 0x01,
	0x00, 0x00,
}
