// Code generated by protoc-gen-go. DO NOT EDIT.
// source: QuitGroup.proto

package QuitGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QuitGroupInner struct {
	Quitor               *uint64  `protobuf:"varint,1,opt,name=quitor" json:"quitor,omitempty"`
	GroupId              *uint64  `protobuf:"varint,2,req,name=groupId" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupInner) Reset()         { *m = QuitGroupInner{} }
func (m *QuitGroupInner) String() string { return proto.CompactTextString(m) }
func (*QuitGroupInner) ProtoMessage()    {}
func (*QuitGroupInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_067ad62f2ad066c9, []int{0}
}

func (m *QuitGroupInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupInner.Unmarshal(m, b)
}
func (m *QuitGroupInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupInner.Marshal(b, m, deterministic)
}
func (m *QuitGroupInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupInner.Merge(m, src)
}
func (m *QuitGroupInner) XXX_Size() int {
	return xxx_messageInfo_QuitGroupInner.Size(m)
}
func (m *QuitGroupInner) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupInner.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupInner proto.InternalMessageInfo

func (m *QuitGroupInner) GetQuitor() uint64 {
	if m != nil && m.Quitor != nil {
		return *m.Quitor
	}
	return 0
}

func (m *QuitGroupInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*QuitGroupInner)(nil), "QuitGroupInner")
}

func init() { proto.RegisterFile("QuitGroup.proto", fileDescriptor_067ad62f2ad066c9) }

var fileDescriptor_067ad62f2ad066c9 = []byte{
	// 91 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0f, 0x2c, 0xcd, 0x2c,
	0x71, 0x2f, 0xca, 0x2f, 0x2d, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe2, 0xe2, 0x83,
	0x0b, 0x79, 0xe6, 0xe5, 0xa5, 0x16, 0x09, 0x89, 0x71, 0xb1, 0x15, 0x96, 0x66, 0x96, 0xe4, 0x17,
	0x49, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x41, 0x79, 0x42, 0x12, 0x5c, 0xec, 0xe9, 0x60, 0x55,
	0x29, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0x2c, 0x41, 0x30, 0xae, 0x13, 0x93, 0x07, 0x33, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x30, 0x37, 0x27, 0xb2, 0x59, 0x00, 0x00, 0x00,
}
