// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SearchGroups.proto

package SearchGroups

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchGroupsInner struct {
	Asker                *uint64  `protobuf:"varint,1,opt,name=asker" json:"asker,omitempty"`
	SearchType           *uint32  `protobuf:"varint,2,opt,name=searchType" json:"searchType,omitempty"`
	Keywords             *string  `protobuf:"bytes,3,opt,name=keywords" json:"keywords,omitempty"`
	PageNo               *uint32  `protobuf:"varint,4,opt,name=pageNo" json:"pageNo,omitempty"`
	PageSize             *uint32  `protobuf:"varint,5,opt,name=pageSize" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchGroupsInner) Reset()         { *m = SearchGroupsInner{} }
func (m *SearchGroupsInner) String() string { return proto.CompactTextString(m) }
func (*SearchGroupsInner) ProtoMessage()    {}
func (*SearchGroupsInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fa7ac4df0047324, []int{0}
}

func (m *SearchGroupsInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchGroupsInner.Unmarshal(m, b)
}
func (m *SearchGroupsInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchGroupsInner.Marshal(b, m, deterministic)
}
func (m *SearchGroupsInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchGroupsInner.Merge(m, src)
}
func (m *SearchGroupsInner) XXX_Size() int {
	return xxx_messageInfo_SearchGroupsInner.Size(m)
}
func (m *SearchGroupsInner) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchGroupsInner.DiscardUnknown(m)
}

var xxx_messageInfo_SearchGroupsInner proto.InternalMessageInfo

func (m *SearchGroupsInner) GetAsker() uint64 {
	if m != nil && m.Asker != nil {
		return *m.Asker
	}
	return 0
}

func (m *SearchGroupsInner) GetSearchType() uint32 {
	if m != nil && m.SearchType != nil {
		return *m.SearchType
	}
	return 0
}

func (m *SearchGroupsInner) GetKeywords() string {
	if m != nil && m.Keywords != nil {
		return *m.Keywords
	}
	return ""
}

func (m *SearchGroupsInner) GetPageNo() uint32 {
	if m != nil && m.PageNo != nil {
		return *m.PageNo
	}
	return 0
}

func (m *SearchGroupsInner) GetPageSize() uint32 {
	if m != nil && m.PageSize != nil {
		return *m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchGroupsInner)(nil), "SearchGroupsInner")
}

func init() { proto.RegisterFile("SearchGroups.proto", fileDescriptor_5fa7ac4df0047324) }

var fileDescriptor_5fa7ac4df0047324 = []byte{
	// 180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0a, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0x70, 0x2f, 0xca, 0x2f, 0x2d, 0x28, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a,
	0xc9, 0xc8, 0x25, 0x88, 0x2c, 0xec, 0x99, 0x97, 0x97, 0x5a, 0x24, 0x24, 0xc2, 0xc5, 0x9a, 0x58,
	0x9c, 0x9d, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x12, 0x04, 0xe1, 0x08, 0xc9, 0x71, 0x71,
	0x15, 0x83, 0x95, 0x86, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0x21, 0x89,
	0x08, 0x49, 0x71, 0x71, 0x64, 0xa7, 0x56, 0x96, 0xe7, 0x17, 0xa5, 0x14, 0x4b, 0x30, 0x2b, 0x30,
	0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0x05, 0x89, 0xe9, 0xa9, 0x7e, 0xf9, 0x12,
	0x2c, 0x60, 0x7d, 0x50, 0x1e, 0x48, 0x0f, 0x88, 0x15, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0x0a, 0x96,
	0x81, 0xf3, 0x9d, 0xd4, 0xb8, 0x94, 0x92, 0xf3, 0x73, 0xf5, 0x2a, 0x4b, 0xf3, 0x4a, 0xf2, 0xf3,
	0xd2, 0x2b, 0x4a, 0xf3, 0xf4, 0x72, 0xf2, 0xd3, 0x33, 0x93, 0xf5, 0x92, 0xf3, 0x8b, 0x52, 0x21,
	0xce, 0x4f, 0x2a, 0x4d, 0xf3, 0x60, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x98, 0x89, 0xcf, 0xf7,
	0xd8, 0x00, 0x00, 0x00,
}
