// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SendGroupMsgResp.proto

package SendGroupMsgResp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendGroupMsgRespInner struct {
	Token                *string  `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Url                  *string  `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendGroupMsgRespInner) Reset()         { *m = SendGroupMsgRespInner{} }
func (m *SendGroupMsgRespInner) String() string { return proto.CompactTextString(m) }
func (*SendGroupMsgRespInner) ProtoMessage()    {}
func (*SendGroupMsgRespInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_94065952708d9859, []int{0}
}

func (m *SendGroupMsgRespInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendGroupMsgRespInner.Unmarshal(m, b)
}
func (m *SendGroupMsgRespInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendGroupMsgRespInner.Marshal(b, m, deterministic)
}
func (m *SendGroupMsgRespInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendGroupMsgRespInner.Merge(m, src)
}
func (m *SendGroupMsgRespInner) XXX_Size() int {
	return xxx_messageInfo_SendGroupMsgRespInner.Size(m)
}
func (m *SendGroupMsgRespInner) XXX_DiscardUnknown() {
	xxx_messageInfo_SendGroupMsgRespInner.DiscardUnknown(m)
}

var xxx_messageInfo_SendGroupMsgRespInner proto.InternalMessageInfo

func (m *SendGroupMsgRespInner) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *SendGroupMsgRespInner) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*SendGroupMsgRespInner)(nil), "SendGroupMsgRespInner")
}

func init() { proto.RegisterFile("SendGroupMsgResp.proto", fileDescriptor_94065952708d9859) }

var fileDescriptor_94065952708d9859 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0b, 0x4e, 0xcd, 0x4b,
	0x71, 0x2f, 0xca, 0x2f, 0x2d, 0xf0, 0x2d, 0x4e, 0x0f, 0x4a, 0x2d, 0x2e, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0xb2, 0xe7, 0x12, 0x45, 0x97, 0xf1, 0xcc, 0xcb, 0x4b, 0x2d, 0x12, 0x12, 0xe1,
	0x62, 0x2d, 0xc9, 0xcf, 0x4e, 0xcd, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84,
	0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x72, 0x24, 0x98, 0xc0, 0x62, 0x20, 0xa6, 0x13, 0x93, 0x07, 0x33,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x16, 0x49, 0x2a, 0xf0, 0x5d, 0x00, 0x00, 0x00,
}
