// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SendGroupMsg.proto

package SendGroupMsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendGroupMsgInner struct {
	MsgType              *uint32  `protobuf:"varint,1,req,name=msgType" json:"msgType,omitempty"`
	MsgId                *string  `protobuf:"bytes,2,opt,name=msgId" json:"msgId,omitempty"`
	MsgContent           []byte   `protobuf:"bytes,3,opt,name=msgContent" json:"msgContent,omitempty"`
	MsgSender            *uint64  `protobuf:"varint,4,opt,name=msgSender" json:"msgSender,omitempty"`
	MsgReceiver          *uint64  `protobuf:"varint,5,opt,name=msgReceiver" json:"msgReceiver,omitempty"`
	MsgDomain            *string  `protobuf:"bytes,6,opt,name=msgDomain" json:"msgDomain,omitempty"`
	MsgFileName          *string  `protobuf:"bytes,7,opt,name=msgFileName" json:"msgFileName,omitempty"`
	MsgCompressLen       *uint32  `protobuf:"varint,8,opt,name=msgCompressLen" json:"msgCompressLen,omitempty"`
	MsgData              []byte   `protobuf:"bytes,9,opt,name=msgData" json:"msgData,omitempty"`
	Anonymity            *uint32  `protobuf:"varint,10,opt,name=anonymity" json:"anonymity,omitempty"`
	ExtOpts              *string  `protobuf:"bytes,11,opt,name=extOpts" json:"extOpts,omitempty"`
	GroupId              *uint64  `protobuf:"varint,12,req,name=groupId" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendGroupMsgInner) Reset()         { *m = SendGroupMsgInner{} }
func (m *SendGroupMsgInner) String() string { return proto.CompactTextString(m) }
func (*SendGroupMsgInner) ProtoMessage()    {}
func (*SendGroupMsgInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a1bd22c11b1ba7b, []int{0}
}

func (m *SendGroupMsgInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendGroupMsgInner.Unmarshal(m, b)
}
func (m *SendGroupMsgInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendGroupMsgInner.Marshal(b, m, deterministic)
}
func (m *SendGroupMsgInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendGroupMsgInner.Merge(m, src)
}
func (m *SendGroupMsgInner) XXX_Size() int {
	return xxx_messageInfo_SendGroupMsgInner.Size(m)
}
func (m *SendGroupMsgInner) XXX_DiscardUnknown() {
	xxx_messageInfo_SendGroupMsgInner.DiscardUnknown(m)
}

var xxx_messageInfo_SendGroupMsgInner proto.InternalMessageInfo

func (m *SendGroupMsgInner) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *SendGroupMsgInner) GetMsgId() string {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return ""
}

func (m *SendGroupMsgInner) GetMsgContent() []byte {
	if m != nil {
		return m.MsgContent
	}
	return nil
}

func (m *SendGroupMsgInner) GetMsgSender() uint64 {
	if m != nil && m.MsgSender != nil {
		return *m.MsgSender
	}
	return 0
}

func (m *SendGroupMsgInner) GetMsgReceiver() uint64 {
	if m != nil && m.MsgReceiver != nil {
		return *m.MsgReceiver
	}
	return 0
}

func (m *SendGroupMsgInner) GetMsgDomain() string {
	if m != nil && m.MsgDomain != nil {
		return *m.MsgDomain
	}
	return ""
}

func (m *SendGroupMsgInner) GetMsgFileName() string {
	if m != nil && m.MsgFileName != nil {
		return *m.MsgFileName
	}
	return ""
}

func (m *SendGroupMsgInner) GetMsgCompressLen() uint32 {
	if m != nil && m.MsgCompressLen != nil {
		return *m.MsgCompressLen
	}
	return 0
}

func (m *SendGroupMsgInner) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *SendGroupMsgInner) GetAnonymity() uint32 {
	if m != nil && m.Anonymity != nil {
		return *m.Anonymity
	}
	return 0
}

func (m *SendGroupMsgInner) GetExtOpts() string {
	if m != nil && m.ExtOpts != nil {
		return *m.ExtOpts
	}
	return ""
}

func (m *SendGroupMsgInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func init() {
	proto.RegisterType((*SendGroupMsgInner)(nil), "SendGroupMsgInner")
}

func init() { proto.RegisterFile("SendGroupMsg.proto", fileDescriptor_8a1bd22c11b1ba7b) }

var fileDescriptor_8a1bd22c11b1ba7b = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x69, 0xa7, 0xe3, 0xd8, 0x3b, 0x33, 0x82, 0xc1, 0xc5, 0x5d, 0x88, 0x04, 0x17, 0x92,
	0x95, 0x0f, 0xa1, 0x83, 0x5a, 0xf0, 0x07, 0xa2, 0x2f, 0x50, 0xec, 0x25, 0x14, 0xcc, 0x0f, 0x49,
	0x14, 0xfb, 0xe4, 0x6e, 0x25, 0xb1, 0xa5, 0xc5, 0xe5, 0xf7, 0x1d, 0x0e, 0x27, 0x37, 0xc0, 0x5e,
	0xc9, 0x74, 0xf7, 0xde, 0x7e, 0xba, 0xa7, 0xa0, 0xae, 0x9d, 0xb7, 0xd1, 0x5e, 0xfe, 0x94, 0x70,
	0xba, 0xd4, 0x8d, 0x31, 0xe4, 0x19, 0xc2, 0x46, 0x07, 0xf5, 0x36, 0x38, 0xc2, 0x82, 0x97, 0x62,
	0x2f, 0x27, 0x64, 0x67, 0xb0, 0xd6, 0x41, 0x35, 0x1d, 0x96, 0xbc, 0x10, 0xb5, 0xfc, 0x03, 0x76,
	0x01, 0xa0, 0x83, 0xba, 0xb5, 0x26, 0x92, 0x89, 0xb8, 0xe2, 0x85, 0xd8, 0xc9, 0x85, 0x61, 0xe7,
	0x50, 0xeb, 0xa0, 0xd2, 0x0e, 0x79, 0xac, 0x78, 0x21, 0x2a, 0x39, 0x0b, 0xc6, 0x61, 0xab, 0x83,
	0x92, 0xf4, 0x4e, 0xfd, 0x17, 0x79, 0x5c, 0xe7, 0x7c, 0xa9, 0xc6, 0xfe, 0xc1, 0xea, 0xb6, 0x37,
	0x78, 0x94, 0x97, 0x67, 0x31, 0xf6, 0xef, 0xfa, 0x0f, 0x7a, 0x6e, 0x35, 0xe1, 0x26, 0xe7, 0x4b,
	0xc5, 0xae, 0xe0, 0x24, 0xbf, 0x46, 0x3b, 0x4f, 0x21, 0x3c, 0x92, 0xc1, 0x63, 0x5e, 0x88, 0xbd,
	0xfc, 0x67, 0xc7, 0xbb, 0x0f, 0x6d, 0x6c, 0xb1, 0xce, 0x47, 0x4c, 0x98, 0x5e, 0xd0, 0x1a, 0x6b,
	0x06, 0xdd, 0xc7, 0x01, 0x21, 0x97, 0x67, 0x91, 0x7a, 0xf4, 0x1d, 0x5f, 0x5c, 0x0c, 0xb8, 0xcd,
	0xeb, 0x13, 0xa6, 0x44, 0xa5, 0xaf, 0x6d, 0x3a, 0xdc, 0xf1, 0x52, 0x54, 0x72, 0xc2, 0x9b, 0xf2,
	0x61, 0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x91, 0x61, 0x39, 0x27, 0x92, 0x01, 0x00, 0x00,
}
