// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SetGroupMemberRole.proto

package SetGroupMemberRole

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SetGroupMemberRoleInner struct {
	GroupId              *uint64  `protobuf:"varint,1,req,name=groupId" json:"groupId,omitempty"`
	MemberId             *uint64  `protobuf:"varint,2,opt,name=memberId" json:"memberId,omitempty"`
	Role                 *uint32  `protobuf:"varint,3,opt,name=role" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetGroupMemberRoleInner) Reset()         { *m = SetGroupMemberRoleInner{} }
func (m *SetGroupMemberRoleInner) String() string { return proto.CompactTextString(m) }
func (*SetGroupMemberRoleInner) ProtoMessage()    {}
func (*SetGroupMemberRoleInner) Descriptor() ([]byte, []int) {
	return fileDescriptor_edf7e5b822627f08, []int{0}
}

func (m *SetGroupMemberRoleInner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetGroupMemberRoleInner.Unmarshal(m, b)
}
func (m *SetGroupMemberRoleInner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetGroupMemberRoleInner.Marshal(b, m, deterministic)
}
func (m *SetGroupMemberRoleInner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetGroupMemberRoleInner.Merge(m, src)
}
func (m *SetGroupMemberRoleInner) XXX_Size() int {
	return xxx_messageInfo_SetGroupMemberRoleInner.Size(m)
}
func (m *SetGroupMemberRoleInner) XXX_DiscardUnknown() {
	xxx_messageInfo_SetGroupMemberRoleInner.DiscardUnknown(m)
}

var xxx_messageInfo_SetGroupMemberRoleInner proto.InternalMessageInfo

func (m *SetGroupMemberRoleInner) GetGroupId() uint64 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *SetGroupMemberRoleInner) GetMemberId() uint64 {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return 0
}

func (m *SetGroupMemberRoleInner) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func init() {
	proto.RegisterType((*SetGroupMemberRoleInner)(nil), "SetGroupMemberRoleInner")
}

func init() { proto.RegisterFile("SetGroupMemberRole.proto", fileDescriptor_edf7e5b822627f08) }

var fileDescriptor_edf7e5b822627f08 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x08, 0x4e, 0x2d, 0x71,
	0x2f, 0xca, 0x2f, 0x2d, 0xf0, 0x4d, 0xcd, 0x4d, 0x4a, 0x2d, 0x0a, 0xca, 0xcf, 0x49, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0x4a, 0xe6, 0x12, 0xc7, 0x94, 0xf3, 0xcc, 0xcb, 0x4b, 0x2d, 0x12,
	0x92, 0xe0, 0x62, 0x4f, 0x07, 0x89, 0x7b, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x04, 0xc1,
	0xb8, 0x42, 0x52, 0x5c, 0x1c, 0xb9, 0x60, 0xc5, 0x9e, 0x29, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x2c,
	0x41, 0x70, 0xbe, 0x90, 0x10, 0x17, 0x4b, 0x51, 0x7e, 0x4e, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x6f, 0x10, 0x98, 0xed, 0xa4, 0xc6, 0xa5, 0x94, 0x9c, 0x9f, 0xab, 0x57, 0x59, 0x9a, 0x57, 0x92,
	0x9f, 0x97, 0x5e, 0x51, 0x9a, 0xa7, 0x97, 0x93, 0x9f, 0x9e, 0x99, 0xac, 0x97, 0x9c, 0x5f, 0x04,
	0x75, 0x47, 0x52, 0x69, 0x9a, 0x07, 0x33, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x11, 0x0b, 0x56,
	0xa7, 0x00, 0x00, 0x00,
}
